/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covid19databank;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import conn.connection;
import conn.positionDetails;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author sasin
 */
public class addVaccine extends javax.swing.JFrame {

    /**
     * Creates new form addVaccine
     */
    String did,dmail,dname;
    Statement st;
    Connection con;
    public addVaccine() {
        
        this.setUndecorated(true);
        setResizable(false);
        initComponents();
        
         //set an icon
         URL image = getClass().getResource("/source/microbe_48px.png");
        ImageIcon img = new ImageIcon(image);
   
        this.setIconImage(img.getImage());
        
        hideErrorMessages();
        
        //get position details
        did = positionDetails.DID;
        dmail = positionDetails.DMAIL;
        dname = positionDetails.DNAME;
        //get connection
        con = connection.connect();
        
        pnlRegisteredPerson.setVisible(false);
    }
    
     public void hideErrorMessages()
    {
        lblErrAddress.setVisible(false);
          lblErrEmail.setVisible(false);
             lblErrId.setVisible(false);
              lblErrName.setVisible(false);
                lblErrTp.setVisible(false);
                lblErrAge.setVisible(false);
                lblErrVacc.setVisible(false);
                lblErrId1.setVisible(false);
                lblErrVacc1.setVisible(false);
                lblErrVaccChose.setVisible(false);
                
                errAddress.setVisible(false);
                errId.setVisible(false);
                errMail.setVisible(false);
                errName.setVisible(false);
                errTp.setVisible(false);
                errAge.setVisible(false);
                 errVacc.setVisible(false);
                 errId1.setVisible(false);
                 errVacc1.setVisible(false);
                 errVaccChose.setVisible(false);
                 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnlBack = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnsecondOrBooster = new javax.swing.JButton();
        pnlRegisteredPerson = new javax.swing.JPanel();
        txtNIC = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblErrId1 = new javax.swing.JLabel();
        errId1 = new javax.swing.JLabel();
        cmboVacc2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        errVacc1 = new javax.swing.JLabel();
        lblErrVacc1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        chkBooster = new javax.swing.JCheckBox();
        chk2nd = new javax.swing.JCheckBox();
        btnBack2 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblErrVaccChose = new javax.swing.JLabel();
        errVaccChose = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        errAddress = new javax.swing.JLabel();
        errTp = new javax.swing.JLabel();
        errMail = new javax.swing.JLabel();
        errId = new javax.swing.JLabel();
        errName = new javax.swing.JLabel();
        lblErrName = new javax.swing.JLabel();
        lblErrAddress = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblErrTp = new javax.swing.JLabel();
        lblErrEmail = new javax.swing.JLabel();
        lblErrId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        errAge = new javax.swing.JLabel();
        lblErrAge = new javax.swing.JLabel();
        cmboVacc = new javax.swing.JComboBox<>();
        errVacc = new javax.swing.JLabel();
        lblErrVacc = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        chkCovidAffected = new javax.swing.JCheckBox();

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Full Name");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Telephone No.");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("E-mail");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("ID No.");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 170, 109));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("x");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 730, 670));

        lblClose.setBackground(new java.awt.Color(104, 170, 109));
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 30));

        lblMinimize.setBackground(new java.awt.Color(104, 170, 109));
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("_");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COVID 19 DATABANK");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        btnsecondOrBooster.setBackground(new java.awt.Color(4, 170, 109));
        btnsecondOrBooster.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnsecondOrBooster.setForeground(new java.awt.Color(255, 255, 255));
        btnsecondOrBooster.setText("2nd Vaccine or Booster");
        btnsecondOrBooster.setActionCommand("");
        btnsecondOrBooster.setBorder(null);
        btnsecondOrBooster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsecondOrBooster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsecondOrBoosterActionPerformed(evt);
            }
        });
        jPanel2.add(btnsecondOrBooster, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 190, 30));

        pnlBack.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 29));

        pnlRegisteredPerson.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegisteredPerson.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNIC.setBackground(new java.awt.Color(241, 241, 241));
        txtNIC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNIC.setForeground(new java.awt.Color(153, 153, 153));
        txtNIC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNIC.setText("Enter person nic no.");
        txtNIC.setBorder(null);
        txtNIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNICMouseClicked(evt);
            }
        });
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNICKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
        });
        pnlRegisteredPerson.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 500, 34));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Vaccine -");
        pnlRegisteredPerson.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, -1));

        lblErrId1.setBackground(new java.awt.Color(0, 0, 0));
        lblErrId1.setForeground(new java.awt.Color(255, 255, 255));
        lblErrId1.setText("Please enter person nic no.!");
        lblErrId1.setOpaque(true);
        pnlRegisteredPerson.add(lblErrId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 150, -1));

        errId1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errId1.setForeground(new java.awt.Color(255, 0, 0));
        errId1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errId1.setText("x");
        errId1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errId1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errId1MouseExited(evt);
            }
        });
        pnlRegisteredPerson.add(errId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 20, 30));

        cmboVacc2.setBackground(new java.awt.Color(241, 241, 241));
        cmboVacc2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmboVacc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the vaccine model", "Sinopharm", "Pfizer", "AstraZeneca", "Moderna" }));
        pnlRegisteredPerson.add(cmboVacc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 500, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Vaccine model");
        pnlRegisteredPerson.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 425, -1));

        errVacc1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errVacc1.setForeground(new java.awt.Color(255, 0, 0));
        errVacc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errVacc1.setText("x");
        errVacc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errVacc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errVacc1MouseExited(evt);
            }
        });
        pnlRegisteredPerson.add(errVacc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 20, 30));

        lblErrVacc1.setBackground(new java.awt.Color(0, 0, 0));
        lblErrVacc1.setForeground(new java.awt.Color(255, 255, 255));
        lblErrVacc1.setText("Please select vaccine model!");
        lblErrVacc1.setOpaque(true);
        pnlRegisteredPerson.add(lblErrVacc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 150, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("NIC");
        pnlRegisteredPerson.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 425, -1));

        chkBooster.setBackground(new java.awt.Color(255, 255, 255));
        chkBooster.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkBooster.setText("Booster");
        pnlRegisteredPerson.add(chkBooster, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        chk2nd.setBackground(new java.awt.Color(255, 255, 255));
        chk2nd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chk2nd.setText("2nd Vaccine");
        pnlRegisteredPerson.add(chk2nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btnBack2.setBackground(new java.awt.Color(4, 170, 109));
        btnBack2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("Back");
        btnBack2.setBorder(null);
        btnBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        pnlRegisteredPerson.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 90, 30));

        btnUpdate.setBackground(new java.awt.Color(4, 170, 109));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlRegisteredPerson.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 90, 30));

        lblErrVaccChose.setBackground(new java.awt.Color(0, 0, 0));
        lblErrVaccChose.setForeground(new java.awt.Color(255, 255, 255));
        lblErrVaccChose.setText("Please chose vaccine type!");
        lblErrVaccChose.setOpaque(true);
        pnlRegisteredPerson.add(lblErrVaccChose, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 150, -1));

        errVaccChose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errVaccChose.setForeground(new java.awt.Color(255, 0, 0));
        errVaccChose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errVaccChose.setText("x");
        errVaccChose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errVaccChoseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errVaccChoseMouseExited(evt);
            }
        });
        pnlRegisteredPerson.add(errVaccChose, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 20, 30));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlRegisteredPerson.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 200, 160));

        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(4, 170, 109), 1, true));
        pnlRegisteredPerson.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 670, 450));

        pnlBack.add(pnlRegisteredPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 730, 650));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(4, 170, 104));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ADD VACCINES");
        pnlBack.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 740, 50));

        errAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errAddress.setForeground(new java.awt.Color(255, 0, 0));
        errAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errAddress.setText("x");
        errAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errAddressMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errAddressMouseExited(evt);
            }
        });
        pnlBack.add(errAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 20, 30));

        errTp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errTp.setForeground(new java.awt.Color(255, 0, 0));
        errTp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errTp.setText("x");
        errTp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errTpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errTpMouseExited(evt);
            }
        });
        pnlBack.add(errTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 20, 30));

        errMail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errMail.setForeground(new java.awt.Color(255, 0, 0));
        errMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errMail.setText("x");
        errMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errMailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errMailMouseExited(evt);
            }
        });
        pnlBack.add(errMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 20, 30));

        errId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errId.setForeground(new java.awt.Color(255, 0, 0));
        errId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errId.setText("x");
        errId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errIdMouseExited(evt);
            }
        });
        pnlBack.add(errId, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 20, 30));

        errName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errName.setForeground(new java.awt.Color(255, 0, 0));
        errName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errName.setText("x");
        errName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errNameMouseExited(evt);
            }
        });
        pnlBack.add(errName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 20, 30));

        lblErrName.setBackground(new java.awt.Color(0, 0, 0));
        lblErrName.setForeground(new java.awt.Color(255, 255, 255));
        lblErrName.setText("Please enter person full name!");
        lblErrName.setOpaque(true);
        pnlBack.add(lblErrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 160, -1));

        lblErrAddress.setBackground(new java.awt.Color(0, 0, 0));
        lblErrAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblErrAddress.setText("Please enter person address!");
        lblErrAddress.setOpaque(true);
        pnlBack.add(lblErrAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 150, -1));

        txtFullName.setBackground(new java.awt.Color(241, 241, 241));
        txtFullName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(153, 153, 153));
        txtFullName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFullName.setText("Enter person full name");
        txtFullName.setBorder(null);
        txtFullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFullNameMouseClicked(evt);
            }
        });
        txtFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFullNameKeyPressed(evt);
            }
        });
        pnlBack.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 500, 34));

        lblErrTp.setBackground(new java.awt.Color(0, 0, 0));
        lblErrTp.setForeground(new java.awt.Color(255, 255, 255));
        lblErrTp.setText("Please enter person Tele.No.!");
        lblErrTp.setOpaque(true);
        pnlBack.add(lblErrTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 160, -1));

        lblErrEmail.setBackground(new java.awt.Color(0, 0, 0));
        lblErrEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblErrEmail.setText("Please enter person e-mail!");
        lblErrEmail.setOpaque(true);
        pnlBack.add(lblErrEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 140, -1));

        lblErrId.setBackground(new java.awt.Color(0, 0, 0));
        lblErrId.setForeground(new java.awt.Color(255, 255, 255));
        lblErrId.setText("Please enter person id no.!");
        lblErrId.setOpaque(true);
        pnlBack.add(lblErrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 140, -1));

        txtId.setBackground(new java.awt.Color(241, 241, 241));
        txtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(153, 153, 153));
        txtId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtId.setText("Enter person id no.");
        txtId.setBorder(null);
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        pnlBack.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 500, 34));

        txtEmail.setBackground(new java.awt.Color(241, 241, 241));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.setText("Enter your e-mail.");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        pnlBack.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 500, 34));

        txtTele.setBackground(new java.awt.Color(241, 241, 241));
        txtTele.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTele.setForeground(new java.awt.Color(153, 153, 153));
        txtTele.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTele.setText("Enter person tele no.");
        txtTele.setBorder(null);
        txtTele.setPreferredSize(new java.awt.Dimension(127, 17));
        txtTele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTeleMouseClicked(evt);
            }
        });
        txtTele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTeleKeyPressed(evt);
            }
        });
        pnlBack.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 500, 34));

        txtAddress.setBackground(new java.awt.Color(241, 241, 241));
        txtAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(153, 153, 153));
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAddress.setText("Enter person address.");
        txtAddress.setBorder(null);
        txtAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddressMouseClicked(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });
        pnlBack.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 500, 34));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Full Name");
        pnlBack.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 425, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Address");
        pnlBack.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 425, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Telephone No.");
        pnlBack.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 425, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("E-mail");
        pnlBack.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 425, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("ID No.");
        pnlBack.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 425, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Age");
        pnlBack.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 425, -1));

        txtAge.setBackground(new java.awt.Color(241, 241, 241));
        txtAge.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(153, 153, 153));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAge.setText("Enter person age");
        txtAge.setBorder(null);
        txtAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgeMouseClicked(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        pnlBack.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 500, 34));

        errAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errAge.setForeground(new java.awt.Color(255, 0, 0));
        errAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errAge.setText("x");
        errAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errAgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errAgeMouseExited(evt);
            }
        });
        pnlBack.add(errAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 20, 30));

        lblErrAge.setBackground(new java.awt.Color(0, 0, 0));
        lblErrAge.setForeground(new java.awt.Color(255, 255, 255));
        lblErrAge.setText("Please enter person age!");
        lblErrAge.setOpaque(true);
        pnlBack.add(lblErrAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 130, -1));

        cmboVacc.setBackground(new java.awt.Color(241, 241, 241));
        cmboVacc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmboVacc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the vaccine model", "Sinopharm", "Pfizer", "AstraZeneca", "Moderna" }));
        pnlBack.add(cmboVacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 500, 30));

        errVacc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errVacc.setForeground(new java.awt.Color(255, 0, 0));
        errVacc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errVacc.setText("x");
        errVacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errVaccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errVaccMouseExited(evt);
            }
        });
        pnlBack.add(errVacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 20, 30));

        lblErrVacc.setBackground(new java.awt.Color(0, 0, 0));
        lblErrVacc.setForeground(new java.awt.Color(255, 255, 255));
        lblErrVacc.setText("Please select your position!");
        lblErrVacc.setOpaque(true);
        pnlBack.add(lblErrVacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 150, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Vaccine");
        pnlBack.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 425, -1));

        btnAdd.setBackground(new java.awt.Color(4, 170, 109));
        btnAdd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setBorder(null);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlBack.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, 340, 30));

        btnBack.setBackground(new java.awt.Color(4, 170, 109));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 90, 30));

        btnClear.setBackground(new java.awt.Color(4, 170, 109));
        btnClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setActionCommand("");
        btnClear.setBorder(null);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlBack.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 90, 30));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlBack.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 340, 230));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlBack.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 160, 160));

        chkCovidAffected.setBackground(new java.awt.Color(255, 255, 255));
        chkCovidAffected.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkCovidAffected.setText("Covid 19 Affected");
        pnlBack.add(chkCovidAffected, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:

        // lblClose.setBackground(Color.getColor("#04aa6d"));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setBackground(Color.RED);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(signIn.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void errAddressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errAddressMouseEntered

        lblErrAddress.setVisible(true);
    }//GEN-LAST:event_errAddressMouseEntered

    private void errAddressMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errAddressMouseExited
        lblErrAddress.setVisible(false);
    }//GEN-LAST:event_errAddressMouseExited

    private void errTpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errTpMouseEntered
        lblErrTp.setVisible(true);
    }//GEN-LAST:event_errTpMouseEntered

    private void errTpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errTpMouseExited
        lblErrTp.setVisible(false);
    }//GEN-LAST:event_errTpMouseExited

    private void errMailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errMailMouseEntered
        lblErrEmail.setVisible(true);
    }//GEN-LAST:event_errMailMouseEntered

    private void errMailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errMailMouseExited
        lblErrEmail.setVisible(false);
    }//GEN-LAST:event_errMailMouseExited

    private void errIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errIdMouseEntered
        lblErrId.setVisible(true);
    }//GEN-LAST:event_errIdMouseEntered

    private void errIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errIdMouseExited
        lblErrId.setVisible(false);
    }//GEN-LAST:event_errIdMouseExited

    private void txtFullNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFullNameMouseClicked
        // TODO add your handling code here:

        txtFullName.setText(null);
        txtFullName.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtFullNameMouseClicked

    private void txtFullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullNameKeyPressed
        // TODO add your handling code here:

        if(txtFullName.getText().length() < 4)
        {

            errName.setVisible(true);
        }
        else
        {
            errName.setVisible(false);
        }
    }//GEN-LAST:event_txtFullNameKeyPressed

    private void errNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errNameMouseEntered
        // TODO add your handling code here:

        lblErrName.setVisible(true);
    }//GEN-LAST:event_errNameMouseEntered

    private void errNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errNameMouseExited
        // TODO add your handling code here:

        lblErrName.setVisible(false);
    }//GEN-LAST:event_errNameMouseExited

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
        // TODO add your handling code here:
        txtId.setText(null);
        txtId.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtIdMouseClicked

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        // TODO add your handling code here:

        if(txtId.getText().length() > 11 || txtId.getText().length() < 9)
        {
            errId.setVisible(true);
        }
        else
        {
            errId.setVisible(false);
        }
        if(txtId.getText().length() == 8)
        {
            lblErrId.setVisible(true);
            lblErrId.setText("eneter capital 'V' ");
        }
        else
        {
            lblErrId.setVisible(false);
            lblErrId.setText("Please enter your id!");
        }

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_V)
        {
            txtId.setEditable(true);
        }
        else
        {
            txtId.setEditable(false);
        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
        txtEmail.setText(null);
        txtEmail.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtEmail.getText());

        if(!match.matches())
        {
            errMail.setVisible(true);
        }
        else
        {
            errMail.setVisible(false);
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtTeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTeleMouseClicked
        // TODO add your handling code here:
        txtTele.setText(null);
        txtTele.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTeleMouseClicked

    private void txtTeleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if(Character.isDigit(c) || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
        {
            txtTele.setEditable(true);
        }
        else
        {
            txtTele.setEditable(false);
        }
        if(txtTele.getText().length() < 9 || txtTele.getText().length() > 9)
        {
            errTp.setVisible(true);
        }
        else
        {
            errTp.setVisible(false);
        }
    }//GEN-LAST:event_txtTeleKeyPressed

    private void txtAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddressMouseClicked
        // TODO add your handling code here:
        txtAddress.setText(null);
        txtAddress.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtAddressMouseClicked

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
        // TODO add your handling code here:

        if(txtAddress.getText().length() < 4)
        {
            errAddress.setVisible(true);
        }
        else
        {
            errAddress.setVisible(false);
        }

    }//GEN-LAST:event_txtAddressKeyPressed

    private void txtAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgeMouseClicked
        // TODO add your handling code here:
         txtAge.setText(null);
        txtAge.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtAgeMouseClicked

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        
        
         char c =evt.getKeyChar();
        
        if(Character.isDigit(c) | evt.getKeyCode() == KeyEvent.VK_BACK_SPACE )
        {
            txtAge.setEditable(true);
        }
        else
        {
             txtAge.setEditable(false);
        }
       
        
    }//GEN-LAST:event_txtAgeKeyPressed

    private void errAgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errAgeMouseEntered
        // TODO add your handling code here:
        lblErrAge.setVisible(true);
    }//GEN-LAST:event_errAgeMouseEntered

    private void errAgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errAgeMouseExited
        // TODO add your handling code here:
        lblErrAge.setVisible(false);
    }//GEN-LAST:event_errAgeMouseExited

    private void errVaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errVaccMouseEntered
        // TODO add your handling code here:
        lblErrVacc.setVisible(true);
    }//GEN-LAST:event_errVaccMouseEntered

    private void errVaccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errVaccMouseExited
        // TODO add your handling code here:
        lblErrVacc.setVisible(false);
    }//GEN-LAST:event_errVaccMouseExited

    private void txtNICMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNICMouseClicked
        // TODO add your handling code here:
        txtNIC.setText(null);
        txtNIC.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_txtNICMouseClicked

    private void txtNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyPressed
        // TODO add your handling code here:
        
       
        if(txtNIC.getText().length() > 11 || txtNIC.getText().length() < 9)
        {
            errId1.setVisible(true);
        }
        else
        {
            errId1.setVisible(false);
        }
        if(txtId.getText().length() == 8)
        {
            lblErrId1.setVisible(true);
            lblErrId1.setText("eneter capital 'V' ");
        }
        else
        {
            lblErrId1.setVisible(false);
            lblErrId1.setText("Please enter your id!");
        }
        
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_V)
        {
            txtNIC.setEditable(true);
        }
        else
        {
            txtNIC.setEditable(false);
        }
           
       
    }//GEN-LAST:event_txtNICKeyPressed

    private void errId1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errId1MouseEntered
        // TODO add your handling code here:
        
        lblErrId1.setVisible(true);
    }//GEN-LAST:event_errId1MouseEntered

    private void errId1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errId1MouseExited
        // TODO add your handling code here:
        lblErrId1.setVisible(false);
    }//GEN-LAST:event_errId1MouseExited

    private void errVacc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errVacc1MouseEntered
        // TODO add your handling code here:
        lblErrVacc1.setVisible(true);
    }//GEN-LAST:event_errVacc1MouseEntered

    private void errVacc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errVacc1MouseExited
        // TODO add your handling code here:
         lblErrVacc1.setVisible(false);
    }//GEN-LAST:event_errVacc1MouseExited

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        
        home obj = new home();
        obj.show();
        this.dispose();

     
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
         home obj = new home();
        obj.show();
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        //vaccine select validation
        if(cmboVacc.getSelectedIndex() == 0)
        {
            errVacc.setVisible(true);
        }
        else
        {
            errVacc.setVisible(false);
        }
        
          //address validate
            if(txtAddress.getText().length() == 0)
                errAddress.setVisible(true);
            else
                 errAddress.setVisible(false);
            
            //age validate
             if(txtAge.getText().length() == 0)
                errAge.setVisible(true);
            else
                 errAge.setVisible(false);
             
              //ID validate
             if(txtId.getText().length() == 0)
                errId.setVisible(true);
            else
                 errId.setVisible(false);
             
             
             //mail validate
             if(txtEmail.getText().length() == 0)
                errMail.setVisible(true);
            else
                 errMail.setVisible(false);
             
              //name validate
             if(txtFullName.getText().length() == 0)
                errName.setVisible(true);
            else
                 errName.setVisible(false);
             
             
              //tele validate
             if(txtTele.getText().length() == 0)
                errTp.setVisible(true);
            else
                 errTp.setVisible(false);
             
             
              //Vaccine validate
             if(cmboVacc.getSelectedIndex() == 0)
                errVacc.setVisible(true);
            else
                 errVacc.setVisible(false);
        
             //find covid affected person
               String covidAffected = "no";
        if(chkCovidAffected.isSelected())
        {
            covidAffected = "yes";
        }
        
        //insert data if validations are true
        if(!errAddress.isVisible() | !errAge.isVisible() | !errId.isVisible() | !errMail.isVisible() | !errName.isVisible() | !errTp.isVisible() | !errVacc.isVisible())
        {
        
            try{
            
            String nic = txtId.getText();
             String name = txtFullName.getText();
              String email = txtEmail.getText();
                int tp = Integer.parseInt(txtTele.getText());
                    String vaccine = cmboVacc.getSelectedItem().toString();
                    int age = Integer.parseInt(txtAge.getText());
                    
                    //create statement
                    st = con.createStatement();
                    
                    //query to insert data
                    String query = "insert into addvacc(nic,name,age,email,tp,1stVac,2ndVac,booster,fullVac,covidAffect) values('" + nic + "','" + name + "'," + age + ",'" + email + "','" + tp + "','" + vaccine + "',"
                            + "'no','no','no','" + covidAffected + "')";
                    
                    //insert position data
                    String query2 = "insert into vaccpositiondetails(pnic,did,dmail,dname) values('" + nic + "','" + did + "','" + dmail + "','" + dname + "');";
                    
                    st.executeUpdate(query);
                    st.executeUpdate(query2);
                    
                    JOptionPane.showMessageDialog(this,"vaccination Successful!");
                    
                     home obj = new home();
                    obj.show();
                    this.dispose();
                    
            }
            catch(ArithmeticException ee)
            {
                 System.out.println(ee.toString());
            }
            catch(Exception e)
            {
                System.out.println(e.toString());
            }
                    
                    
            
        }
      
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnsecondOrBoosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsecondOrBoosterActionPerformed
        // TODO add your handling code here:
        pnlRegisteredPerson.setVisible(true);
        btnsecondOrBooster.setVisible(false);
        cmboVacc.setVisible(false);
     
    }//GEN-LAST:event_btnsecondOrBoosterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
       
        
         if(txtAge.getText().length() == 0)
        {
            errAge.setVisible(true);
        }
        else
        {
            errAge.setVisible(false);
        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void errVaccChoseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errVaccChoseMouseEntered
        // TODO add your handling code here:
        lblErrVaccChose.setVisible(true);
    }//GEN-LAST:event_errVaccChoseMouseEntered

    private void errVaccChoseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errVaccChoseMouseExited
        // TODO add your handling code here:
          lblErrVaccChose.setVisible(false);
    }//GEN-LAST:event_errVaccChoseMouseExited

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased
        // TODO add your handling code here:
         if(txtNIC.getText().length() == 0)
        {
            errId1.setVisible(true);
        }
        else
        {
            errId1.setVisible(false);
        }
    }//GEN-LAST:event_txtNICKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        //validate vaccine select
        if(chk2nd.isSelected() && chkBooster.isSelected())
        {
            errVaccChose.setVisible(true);
        }
        else
        {
            errVaccChose.setVisible(false);
        }
        
        
         if(chk2nd.isSelected() == false && chkBooster.isSelected() == false)
        {
            errVaccChose.setVisible(true);
        }
        else
        {
            errVaccChose.setVisible(false);
        }
        
        
       //validate nic
        if(txtNIC.getText().length() == 0)
        {
            errId1.setVisible(true);
        }
        else
        {
             errId1.setVisible(false);
        }
        
        //validate vaccine model
        if(cmboVacc2.getSelectedIndex() == 0)
        {
            errVacc1.setVisible(true);
        }
       else
        {
             errVacc1.setVisible(false);
        }
        
        
        
        //update if validation true
        if(!errVacc1.isVisible() && !errVaccChose.isVisible() && !errId1.isVisible())
        {
               try{
                   
                   
                   
                   //create statement
                    st = con.createStatement();
                    
                    String queryget = "select nic from addvacc where nic = '" + txtNIC.getText() + "';" ;
                    
                    ResultSet rs = st.executeQuery(queryget);
                    
                    if(rs.next())
                    {
                    
                    //second vaccine
                    if(chk2nd.isSelected())
                    {
                    
                    //query to update data
                    String query = "update addvacc set 2ndVac = '" + cmboVacc2.getSelectedItem() + "' where nic = '" + txtNIC.getText() + "';";
                       st.executeUpdate(query);
                    }
                    
                    if(chkBooster.isSelected())
                    {
                    String query1 = "update addvacc set booster = '" + cmboVacc2.getSelectedItem() + "', fullVac = 'yes' " +" where nic = '" + txtNIC.getText() + "';";
                       st.executeUpdate(query1);
                       
                       
                    }
                    
                      
                    JOptionPane.showMessageDialog(this,"vaccination Successful!");
                    home obj = new home();
                    obj.show();
                    this.dispose();
                    }
                    
                    else{
                        JOptionPane.showMessageDialog(this, "Invalid NIC !!","invalid",JOptionPane.WARNING_MESSAGE);
                    }
                    
              
                 
                  
                    
            }
            catch(ArithmeticException ee)
            {
                 System.out.println(ee.toString());
            }
            catch(Exception e)
            {
                System.out.println(e.toString());
            }    
                        
            
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVaccine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnsecondOrBooster;
    private javax.swing.JCheckBox chk2nd;
    private javax.swing.JCheckBox chkBooster;
    private javax.swing.JCheckBox chkCovidAffected;
    private javax.swing.JComboBox<String> cmboVacc;
    private javax.swing.JComboBox<String> cmboVacc2;
    private javax.swing.JLabel errAddress;
    private javax.swing.JLabel errAge;
    private javax.swing.JLabel errId;
    private javax.swing.JLabel errId1;
    private javax.swing.JLabel errMail;
    private javax.swing.JLabel errName;
    private javax.swing.JLabel errTp;
    private javax.swing.JLabel errVacc;
    private javax.swing.JLabel errVacc1;
    private javax.swing.JLabel errVaccChose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblErrAddress;
    private javax.swing.JLabel lblErrAge;
    private javax.swing.JLabel lblErrEmail;
    private javax.swing.JLabel lblErrId;
    private javax.swing.JLabel lblErrId1;
    private javax.swing.JLabel lblErrName;
    private javax.swing.JLabel lblErrTp;
    private javax.swing.JLabel lblErrVacc;
    private javax.swing.JLabel lblErrVacc1;
    private javax.swing.JLabel lblErrVaccChose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlRegisteredPerson;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables
}
