/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covid19databank;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import conn.connection;
import conn.vaccinedPData;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sasin
 */
public class fullVaccinedPersons extends javax.swing.JFrame {

    /**
     * Creates new form fullVaccinedPersons
     */
     Connection con;
    Statement st;
    
    public fullVaccinedPersons() {
         this.setUndecorated(true);
        setResizable(false);
        initComponents();
        
         //set an icon
         URL image = getClass().getResource("/source/microbe_48px.png");
        ImageIcon img = new ImageIcon(image);
   
        this.setIconImage(img.getImage());
        
          //get connection
        con = connection.connect();
        st = null;
        
               //table details
        tableDetail();

        //get table data
        getData();

       
    }
    
     public void tableDetail() {
        tblVaccinedPerson.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        tblVaccinedPerson.getTableHeader().setOpaque(false);
        tblVaccinedPerson.getTableHeader().setBackground(new Color(4, 170, 109));
        tblVaccinedPerson.getTableHeader().setForeground(new Color(255, 255, 255));
        tblVaccinedPerson.setRowHeight(25);

    }

    public void getData() {

        try {

            //create statement
            st = con.createStatement();

            //count full vaccined perosons
            String query1 = "select count(id) from addvacc where fullVac = 'yes';";

            ResultSet rs1 = st.executeQuery(query1);

            if (rs1.next()) {
                //call vaccine data method 
                vaccinedPData.count();
                double avg = (rs1.getInt("count(id)") / (vaccinedPData.COUNT * 1.0)) * 100.0;
                DecimalFormat df = new DecimalFormat("####0.00");
                lbltotalAffected.setText(Integer.toString(rs1.getInt("count(id)")));
                lblAVGAffected.setText(df.format(avg) + "%");

            }

      
            //get all full vaccined persons details
            String query = "select * from addvacc where fullVac = 'yes';";

            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
 
                String nic = rs.getString("nic");
                String name = rs.getString("name");
                String age = rs.getString("age");
                String vacc1 = rs.getString("1stVac");
                String vacc2 = rs.getString("2ndVac");
                String booster = rs.getString("booster");
                String fulVac = rs.getString("fullVac");
                
                String tbData[] = {nic,name,age,vacc1,vacc2,booster,fulVac};
                
                DefaultTableModel tblModel = (DefaultTableModel)tblVaccinedPerson.getModel();
                
                tblModel.addRow(tbData);

            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccinedPerson = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbltotalAffected1 = new javax.swing.JLabel();
        lblAVGAffected1 = new javax.swing.JLabel();
        lblAVGAffected = new javax.swing.JLabel();
        lbltotalAffected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(4, 170, 109));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblVaccinedPerson.setAutoCreateRowSorter(true);
        tblVaccinedPerson.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblVaccinedPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Name", "Age", "1st Vaccine", "2nd Vaccine", "Booster", "Full Vaccined"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVaccinedPerson.setFocusable(false);
        tblVaccinedPerson.setGridColor(new java.awt.Color(255, 255, 255));
        tblVaccinedPerson.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblVaccinedPerson.setRowHeight(25);
        tblVaccinedPerson.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblVaccinedPerson.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblVaccinedPerson.setShowVerticalLines(false);
        tblVaccinedPerson.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblVaccinedPerson);
        if (tblVaccinedPerson.getColumnModel().getColumnCount() > 0) {
            tblVaccinedPerson.getColumnModel().getColumn(0).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(1).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(2).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(3).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(4).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(5).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 760, 280));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(4, 170, 104));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("FULL VACCINED PERSONS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, 60));

        jLabel2.setBackground(new java.awt.Color(4, 170, 109));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 29, 450, 23));

        btnBack.setBackground(new java.awt.Color(4, 170, 109));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 100, 30));

        btnDelete.setBackground(new java.awt.Color(4, 170, 109));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 100, 30));

        btnReport.setBackground(new java.awt.Color(255, 255, 255));
        btnReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/download_graph_report_32px.png"))); // NOI18N
        btnReport.setBorder(null);
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 40, 30));

        jLabel1.setBackground(new java.awt.Color(4, 170, 109));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 820, 10));

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setForeground(new java.awt.Color(255, 0, 0));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 20));

        lblMinimize.setBackground(new java.awt.Color(255, 255, 255));
        lblMinimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(4, 170, 109));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 20));

        txtSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(204, 204, 204));
        txtSearch.setText("Search by NIC");
        txtSearch.setBorder(null);
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, -1));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/search_24px.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 30, 30));

        jSeparator1.setForeground(new java.awt.Color(4, 170, 109));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 20));

        lbltotalAffected1.setBackground(new java.awt.Color(153, 153, 153));
        lbltotalAffected1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltotalAffected1.setForeground(new java.awt.Color(255, 102, 102));
        lbltotalAffected1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltotalAffected1.setText("TOTAL FULL VACCINED PERSONS : ");
        jPanel1.add(lbltotalAffected1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 390, -1));

        lblAVGAffected1.setBackground(new java.awt.Color(153, 153, 153));
        lblAVGAffected1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAVGAffected1.setForeground(new java.awt.Color(255, 102, 102));
        lblAVGAffected1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAVGAffected1.setText("AVARAGE FULL VACCINED PERSONS : ");
        jPanel1.add(lblAVGAffected1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 390, -1));

        lblAVGAffected.setBackground(new java.awt.Color(153, 153, 153));
        lblAVGAffected.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAVGAffected.setForeground(new java.awt.Color(255, 28, 47));
        lblAVGAffected.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAVGAffected.setText("AVARAGE COVID AFFECTED PERSONS : ");
        jPanel1.add(lblAVGAffected, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 50, -1));

        lbltotalAffected.setBackground(new java.awt.Color(153, 153, 153));
        lbltotalAffected.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltotalAffected.setForeground(new java.awt.Color(255, 28, 47));
        lbltotalAffected.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltotalAffected.setText("TOTAL COVID AFFECTED PERSONS");
        jPanel1.add(lbltotalAffected, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        home obj = new home();
        obj.show();
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        try{

            int row = tblVaccinedPerson.getSelectedRow();
            String cell = tblVaccinedPerson.getModel().getValueAt(row,0).toString();
            String query = "delete from addvacc where nic = '" + cell + "'";

            st = con.createStatement();

            int d =  JOptionPane.showConfirmDialog(this,"delete","Do you want to delete this data?",JOptionPane.WARNING_MESSAGE);

            if(d == 0)
            {
                st.executeUpdate(query);
                //clear table
                tblVaccinedPerson.setModel(new DefaultTableModel(null,new String [] {"NIC","name","Age","1st Vaccine","2nd Vaccine","Booster","Full Vaccined"}));
                getData();

            }

        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:

        //file saving path
        File file = new File("VaccinedPersons.txt");

        try{
            //make a new file
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            fw.write("\t\t---Covid Vaccined Persons List----");
            fw.write("\n\n");

            fw.write("\tNIC   |   NAME   |  AGE  |  1st Vaccine  | 1st Vaccine | BOOSTER\n");

            bw.newLine();
            bw.newLine();

            for(int i = 0; i < tblVaccinedPerson.getRowCount(); i++){//rows

                for(int j = 0; j < tblVaccinedPerson.getColumnCount(); j++){//columns

                    bw.write("\t| " + tblVaccinedPerson.getValueAt(i,j).toString() + "\t" );

                }
                bw.newLine();
            }

            bw.close();
            fw.close();

            JOptionPane.showMessageDialog(this, "Report has been genareted!","report",JOptionPane.INFORMATION_MESSAGE);
        }catch(IOException e)
        {
            System.out.println(e.toString());
        }
        catch(Exception ee)
        {
            System.out.println(ee.toString());
        }

    }//GEN-LAST:event_btnReportActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:

        // lblClose.setBackground(Color.getColor("#04aa6d"));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setBackground(Color.RED);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(home.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
        txtSearch.setText(null);
        txtSearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtSearchMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        try {

            //create statement
            st = con.createStatement();

            String search = txtSearch.getText();

            //get all vaccined persons details
            String query = "select * from addvacc where nic like '" + search + "%';";

            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                 tblVaccinedPerson.setModel(new DefaultTableModel(null,new String [] {"NIC","name","Age","1st Vaccine","2nd Vaccine","Booster","Full Vaccined"}));

               
                String nic = rs.getString("nic");
                String name = rs.getString("name");
                String age = rs.getString("age");
                String vacc1 = rs.getString("1stVac");
                String vacc2 = rs.getString("2ndVac");
                String booster = rs.getString("booster");
                String fulVac = rs.getString("fullVac");
                
                String tbData[] = {nic,name,age,vacc1,vacc2,booster,fulVac};
             
                DefaultTableModel tblModel = (DefaultTableModel)tblVaccinedPerson.getModel();

                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fullVaccinedPersons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fullVaccinedPersons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fullVaccinedPersons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fullVaccinedPersons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fullVaccinedPersons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAVGAffected;
    private javax.swing.JLabel lblAVGAffected1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lbltotalAffected;
    private javax.swing.JLabel lbltotalAffected1;
    private javax.swing.JTable tblVaccinedPerson;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
