/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covid19databank;

import java.awt.Color;
import conn.connection;
import conn.getid;
import conn.positionDetails;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import conn.positionDetails;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sasin
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    String UID;
    Connection con;
    Statement st;

    public home() {

        this.setUndecorated(true);
        setResizable(false);
        initComponents();

         //set an icon
         URL image = getClass().getResource("/source/microbe_48px.png");
        ImageIcon img = new ImageIcon(image);
   
        this.setIconImage(img.getImage());
        
        //get connection
        con = connection.connect();
        st = null;
        
        
        //get the user id
        UID = getid.getUid();
        
        //display id
        gettingId();
    }
    
    public void gettingId()
    {
        try{
            st = con.createStatement();
            String query = "select * from  userdetails where id = '" + UID + "';";
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next())
            {
                lblName.setText("Name: " + rs.getString("name"));
                lblMail.setText("E-mail: " + rs.getString("email"));
                lblHospital.setText("Hospital: " + rs.getString("hospital"));
                lblNic.setText("NIC: " + rs.getString("idNo"));
                lblPosition.setText("Position: " + rs.getString("position"));
                
                positionDetails.position(UID,rs.getString("email") ,rs.getString("name"));
        
            }
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCurrentPatient = new javax.swing.JButton();
        btnVaccined = new javax.swing.JButton();
        btnAffected = new javax.swing.JButton();
        btnDeaths = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnFullVaccined = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblNic = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblHospital = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 170, 109));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setBackground(new java.awt.Color(104, 170, 109));
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 30));

        lblMinimize.setBackground(new java.awt.Color(104, 170, 109));
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("_");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COVID 19 DATABANK");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 29));

        btnCurrentPatient.setBackground(new java.awt.Color(173, 244, 177));
        btnCurrentPatient.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCurrentPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/physical_therapy_32px.png"))); // NOI18N
        btnCurrentPatient.setText("Current C19 Patient List");
        btnCurrentPatient.setBorder(null);
        btnCurrentPatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCurrentPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentPatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnCurrentPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 250, 80));

        btnVaccined.setBackground(new java.awt.Color(173, 244, 177));
        btnVaccined.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVaccined.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/syringe_50px.png"))); // NOI18N
        btnVaccined.setText("Vaccined Persons List");
        btnVaccined.setBorder(null);
        btnVaccined.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVaccined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccinedActionPerformed(evt);
            }
        });
        jPanel1.add(btnVaccined, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 80));

        btnAffected.setBackground(new java.awt.Color(173, 244, 177));
        btnAffected.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAffected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/expand_influence_32px.png"))); // NOI18N
        btnAffected.setText("Covid 19 Affected Persons");
        btnAffected.setBorder(null);
        btnAffected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAffected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAffectedActionPerformed(evt);
            }
        });
        jPanel1.add(btnAffected, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 250, 80));

        btnDeaths.setBackground(new java.awt.Color(173, 244, 177));
        btnDeaths.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDeaths.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/dead_32px.png"))); // NOI18N
        btnDeaths.setText("Deaths");
        btnDeaths.setBorder(null);
        btnDeaths.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeathsActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 250, 80));

        btnAdd.setBackground(new java.awt.Color(173, 244, 177));
        btnAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/add_24px.png"))); // NOI18N
        btnAdd.setText("Add a Vaccined To Person");
        btnAdd.setBorder(null);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 250, 80));

        btnFullVaccined.setBackground(new java.awt.Color(173, 244, 177));
        btnFullVaccined.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFullVaccined.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/coronavirus_pandemic_64px.png"))); // NOI18N
        btnFullVaccined.setText("Full Vaccined Persons ");
        btnFullVaccined.setBorder(null);
        btnFullVaccined.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFullVaccined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFullVaccinedActionPerformed(evt);
            }
        });
        jPanel1.add(btnFullVaccined, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 80));

        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name ");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 790, -1));

        lblMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMail.setForeground(new java.awt.Color(102, 102, 102));
        lblMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMail.setText("E-mail");
        jPanel1.add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 790, -1));

        lblNic.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNic.setForeground(new java.awt.Color(102, 102, 102));
        lblNic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNic.setText("NIC");
        jPanel1.add(lblNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 790, -1));

        lblPosition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(102, 102, 102));
        lblPosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosition.setText("Position ");
        jPanel1.add(lblPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 790, -1));

        lblHospital.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHospital.setForeground(new java.awt.Color(102, 102, 102));
        lblHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospital.setText("Hospital ");
        jPanel1.add(lblHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 790, -1));

        btnLogout.setBackground(new java.awt.Color(4, 170, 109));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log Out");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 110, 30));

        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(4, 170, 109), 1, true));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 790, 250));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 210, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(home.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setBackground(Color.RED);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:

        // lblClose.setBackground(Color.getColor("#04aa6d"));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int d = JOptionPane.showConfirmDialog(this, "Do you want to log out?","log out",JOptionPane.WARNING_MESSAGE);
        if(d == 0)
        {
        Login obj = new Login();
        obj.show();
        this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnVaccinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccinedActionPerformed
        // TODO add your handling code here:
        vaccinedPersons obj = new vaccinedPersons();
        obj.show();
        this.dispose();
        
    }//GEN-LAST:event_btnVaccinedActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        
        
        addVaccine obj = new addVaccine();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAffectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAffectedActionPerformed
        // TODO add your handling code here:
        
        covidAffectedPersons obj = new covidAffectedPersons();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnAffectedActionPerformed

    private void btnCurrentPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentPatientActionPerformed
        // TODO add your handling code here:
        affectedPersons obj = new affectedPersons();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnCurrentPatientActionPerformed

    private void btnFullVaccinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFullVaccinedActionPerformed
        // TODO add your handling code here:
        
        fullVaccinedPersons obj = new fullVaccinedPersons();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnFullVaccinedActionPerformed

    private void btnDeathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeathsActionPerformed
        // TODO add your handling code here:
        DeathPersons obj = new DeathPersons();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnDeathsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAffected;
    private javax.swing.JButton btnCurrentPatient;
    private javax.swing.JButton btnDeaths;
    private javax.swing.JButton btnFullVaccined;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnVaccined;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblPosition;
    // End of variables declaration//GEN-END:variables
}
