/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covid19databank;

import java.awt.Color;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import conn.getid;
import conn.connection;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sasin
 */
public class personDetails extends javax.swing.JFrame {

    /**
     * Creates new form personDetails
     */
    Statement st;
    Connection con;
    String NIC;
    public personDetails() {
          this.setUndecorated(true);
        setResizable(false);
        initComponents();
        
        con = connection.connect();
        st = null;
        NIC = getid.nic;
        
          //set an icon
         URL image = getClass().getResource("/source/microbe_48px.png");
        ImageIcon img = new ImageIcon(image);
   
        this.setIconImage(img.getImage());
        
        //get person details
        getData(NIC);
        
        //get position details
        getPositionData(NIC);
        
       
    }

    //get person details
    public void getData(String nic)
    {
        try{
            
            st = con.createStatement();
            
            String query = "select * from addvacc where nic = '" + nic + "';";
            
            ResultSet rs = st.executeQuery(query);
            
            
            if(rs.next())
            {
                lblAddress.setText("Tele: " + rs.getString("tp"));
                lblName.setText("Full Name: " + rs.getString("name"));
                lblAge.setText("Age: " + rs.getString("age"));
                lbl1stVac.setText("1st Vaccine: " + rs.getString("1stVac"));
                lbl2ndVacc.setText("2nd Vaccine: " + rs.getString("2ndVac"));
                lblNamee.setText(rs.getString("name"));
                lblBooster.setText("Booster: " + rs.getString("booster"));
                lblMail.setText("E-mail: " + rs.getString("email"));
                lblNic.setText("NIC: " + rs.getString("nic"));
                
                
                
                if(!"no".equals(rs.getString("booster")))
                {
                     System.out.println(rs.getString("booster"));
                }
                else
                {
                     lblVerified.setVisible(false);
                }
                
                
            }
            
        }catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    
    public void getPositionData(String nic)
    {
        try{
            
            st = con.createStatement();
            
            String query = "select did from vaccpositiondetails where pnic = '" + nic + "';";
            
            ResultSet rs = st.executeQuery(query);
            
            
            
            if(rs.next())
            {
                String did = rs.getString("did");
            
                String query1 = "select * from userdetails where id = '" + did + "';";
                
                  ResultSet rs1 = st.executeQuery(query1);
                  
                  if(rs1.next())
                  {
                
                lblHospital.setText("Hospital: " + rs1.getString("hospital"));
                lblVPMail.setText("E-mail: " + rs1.getString("email"));
                lblVPNIC.setText("NIC: " + rs1.getString("idNo"));
                lblVPPosition.setText("Position: " + rs1.getString("position"));
                lblVPName.setText("Full Name: " + rs1.getString("name"));
                  }
              
                
                
            }
            
        }catch(Exception e)
        {
            //System.out.println(e.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblNic = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblBooster = new javax.swing.JLabel();
        btnReportGenarate = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        lbl1stVac = new javax.swing.JLabel();
        lbl2ndVacc = new javax.swing.JLabel();
        lblNamee = new javax.swing.JLabel();
        lblVPName = new javax.swing.JLabel();
        lblVPMail = new javax.swing.JLabel();
        lblVPNIC = new javax.swing.JLabel();
        lblVPPosition = new javax.swing.JLabel();
        lblHospital = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogout1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblVerified = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 56, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 170, 109));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("x");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 730, 670));

        lblClose.setBackground(new java.awt.Color(104, 170, 109));
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 30));

        lblMinimize.setBackground(new java.awt.Color(104, 170, 109));
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("_");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COVID 19 DATABANK");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 29));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(4, 170, 104));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Vaccined Person Details");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 760, 30));

        lblName.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name ");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 760, -1));

        lblMail.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblMail.setForeground(new java.awt.Color(102, 102, 102));
        lblMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMail.setText("E-mail");
        jPanel1.add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 760, -1));

        lblNic.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblNic.setForeground(new java.awt.Color(102, 102, 102));
        lblNic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNic.setText("NIC");
        jPanel1.add(lblNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 760, -1));

        lblAge.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblAge.setForeground(new java.awt.Color(102, 102, 102));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAge.setText("Age");
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 760, -1));

        lblBooster.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblBooster.setForeground(new java.awt.Color(255, 56, 56));
        lblBooster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBooster.setText("Booster");
        jPanel1.add(lblBooster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 760, -1));

        btnReportGenarate.setBackground(new java.awt.Color(255, 255, 255));
        btnReportGenarate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReportGenarate.setForeground(new java.awt.Color(255, 255, 255));
        btnReportGenarate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/download_graph_report_32px.png"))); // NOI18N
        btnReportGenarate.setBorder(null);
        btnReportGenarate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportGenarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportGenarateActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportGenarate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 40, 40));

        lblAddress.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(102, 102, 102));
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress.setText("Address");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 760, -1));

        lbl1stVac.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl1stVac.setForeground(new java.awt.Color(255, 56, 56));
        lbl1stVac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1stVac.setText("1st Vaccine");
        jPanel1.add(lbl1stVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 760, -1));

        lbl2ndVacc.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl2ndVacc.setForeground(new java.awt.Color(255, 56, 56));
        lbl2ndVacc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2ndVacc.setText("2st Vaccine");
        jPanel1.add(lbl2ndVacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 760, -1));

        lblNamee.setBackground(new java.awt.Color(255, 255, 255));
        lblNamee.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNamee.setForeground(new java.awt.Color(4, 170, 104));
        lblNamee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamee.setText("Person Details");
        jPanel1.add(lblNamee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 760, 30));

        lblVPName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVPName.setForeground(new java.awt.Color(102, 102, 102));
        lblVPName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVPName.setText("Name ");
        jPanel1.add(lblVPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 760, -1));

        lblVPMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVPMail.setForeground(new java.awt.Color(102, 102, 102));
        lblVPMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVPMail.setText("E-mail");
        jPanel1.add(lblVPMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 760, -1));

        lblVPNIC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVPNIC.setForeground(new java.awt.Color(102, 102, 102));
        lblVPNIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVPNIC.setText("NIC");
        jPanel1.add(lblVPNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 760, -1));

        lblVPPosition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVPPosition.setForeground(new java.awt.Color(102, 102, 102));
        lblVPPosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVPPosition.setText("Position ");
        jPanel1.add(lblVPPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 760, -1));

        lblHospital.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHospital.setForeground(new java.awt.Color(102, 102, 102));
        lblHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospital.setText("Hospital ");
        jPanel1.add(lblHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 760, -1));

        jSeparator2.setForeground(new java.awt.Color(173, 244, 177));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 340, 10));

        btnLogout1.setBackground(new java.awt.Color(4, 170, 109));
        btnLogout1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout1.setText("Log Out");
        btnLogout1.setBorder(null);
        btnLogout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 80, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 520, 270, 160));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/real.png"))); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 290, 650));

        jSeparator3.setForeground(new java.awt.Color(173, 244, 177));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 580, 10));

        lblVerified.setBackground(new java.awt.Color(4, 170, 109));
        lblVerified.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblVerified.setForeground(new java.awt.Color(4, 170, 109));
        lblVerified.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/instagram_verification_badge_50px.png"))); // NOI18N
        jPanel1.add(lblVerified, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 60, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(4, 170, 104));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("VACCINE CARD");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 760, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:

        // lblClose.setBackground(Color.getColor("#04aa6d"));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setBackground(Color.RED);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(signIn.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
          int d = JOptionPane.showConfirmDialog(this, "Do you want to log out?","log out",JOptionPane.WARNING_MESSAGE);
        if(d == 0)
        {
         Login obj = new Login();
        obj.show();
        this.dispose();
        }
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void btnReportGenarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportGenarateActionPerformed
        // TODO add your handling code here:
        
       

        try{
            //make a new file
            FileWriter fw = new FileWriter("VaccineCard.txt");
            fw.write("\t\t\t__VACCINE CARD__\n\n");
                
                fw.write("\t\t\t");
              fw.write  (lblAddress.getText());
              fw.write("\n");
               fw.write("\t\t\t");
              fw.write  (lblName.getText());
              fw.write("\n");
               fw.write("\t\t\t");
              fw.write  (lblAge.getText());
              fw.write("\n");
               fw.write("\t\t\t");
              fw.write  ( lbl1stVac.getText());
              fw.write("\n");
               fw.write("\t\t\t");
              fw.write  (lbl2ndVacc.getText());
              fw.write("\n");
               fw.write("\t\t\t");
              fw.write  (lblNamee.getText());
              fw.write("\n");
               fw.write("\t\t\t");
              fw.write  (lblBooster.getText());
              fw.write("\n");
               fw.write("\t\t\t");
              fw.write  (lblMail.getText());
              fw.write("\n");
               fw.write("\t\t\t");
              fw.write  (lblNic.getText());
              
              fw.close();
              
              JOptionPane.showMessageDialog(this, "Report Genarated!","report",JOptionPane.INFORMATION_MESSAGE);
            
            
            
        }
        catch(IOException e)
        {
            System.out.println(e.toString());
        }
        catch(Exception ee)
        {
         System.out.println(ee.toString());
        }

      
    }//GEN-LAST:event_btnReportGenarateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnReportGenarate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl1stVac;
    private javax.swing.JLabel lbl2ndVacc;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBooster;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNamee;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblVPMail;
    private javax.swing.JLabel lblVPNIC;
    private javax.swing.JLabel lblVPName;
    private javax.swing.JLabel lblVPPosition;
    private javax.swing.JLabel lblVerified;
    // End of variables declaration//GEN-END:variables
}
