/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covid19databank;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import conn.connection;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author sasin
 */
public class resetPass extends javax.swing.JFrame {

    /**
     * Creates new form resetPass
     */
    
    Statement st;
    Connection con;
    boolean upperDon = false;
    boolean digitDon = false;
    public resetPass() {
        this.setUndecorated(true);
        initComponents();
        
         //set an icon
         URL image = getClass().getResource("/source/microbe_48px.png");
        ImageIcon img = new ImageIcon(image);
   
        this.setIconImage(img.getImage());
        
        //get connection
        con = connection.connect();

        //invisible label hide
        lblInvisiblePsd1.setVisible(false);
        //visible text of password
        txtPassword2.setEchoChar((char) 0);
        txtPassword1.setEchoChar((char) 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblInvisiblePsd = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser1 = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JPasswordField();
        txtPassword2 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        lblInvisiblePsd1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblVisiblePswd1 = new javax.swing.JLabel();
        lblerror = new javax.swing.JLabel();
        lblUpper = new javax.swing.JLabel();
        lblDigit = new javax.swing.JLabel();
        lbl8Char2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUpper1 = new javax.swing.JLabel();

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(4, 170, 104));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOG IN");

        txtUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setText("User");
        txtUser.setBorder(null);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setText("Password");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });

        lblInvisiblePsd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvisiblePsd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/invisible_24px.png"))); // NOI18N
        lblInvisiblePsd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInvisiblePsd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvisiblePsdMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setForeground(new java.awt.Color(104, 170, 109));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 30, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 170, 104));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reset Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 460, 50));

        txtUser1.setBackground(new java.awt.Color(58, 152, 65));
        txtUser1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUser1.setForeground(new java.awt.Color(204, 204, 204));
        txtUser1.setText("User");
        txtUser1.setBorder(null);
        txtUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUser1MouseClicked(evt);
            }
        });
        jPanel1.add(txtUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 160, 270, 30));

        txtPassword1.setBackground(new java.awt.Color(58, 152, 65));
        txtPassword1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword1.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword1.setText("Confirm Password");
        txtPassword1.setBorder(null);
        txtPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassword1MouseClicked(evt);
            }
        });
        jPanel1.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 260, 30));

        txtPassword2.setBackground(new java.awt.Color(58, 152, 65));
        txtPassword2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword2.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword2.setText("Password");
        txtPassword2.setBorder(null);
        txtPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassword2MouseClicked(evt);
            }
        });
        txtPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassword2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassword2KeyReleased(evt);
            }
        });
        jPanel1.add(txtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 230, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 280, 20));

        lblInvisiblePsd1.setBackground(new java.awt.Color(58, 152, 65));
        lblInvisiblePsd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvisiblePsd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/invisible_24px.png"))); // NOI18N
        lblInvisiblePsd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInvisiblePsd1.setOpaque(true);
        lblInvisiblePsd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvisiblePsd1MouseClicked(evt);
            }
        });
        jPanel1.add(lblInvisiblePsd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 40, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 280, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 280, 20));

        jButton1.setBackground(new java.awt.Color(104, 170, 109));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 80, 30));

        jButton2.setBackground(new java.awt.Color(104, 170, 109));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 80, 30));

        lblVisiblePswd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVisiblePswd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/eye_24px_1.png"))); // NOI18N
        lblVisiblePswd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVisiblePswd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVisiblePswd1MouseClicked(evt);
            }
        });
        jPanel1.add(lblVisiblePswd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 30, 30));

        lblerror.setBackground(new java.awt.Color(255, 255, 255));
        lblerror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        lblUpper.setForeground(new java.awt.Color(255, 255, 255));
        lblUpper.setText("* Upper case");
        jPanel1.add(lblUpper, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        lblDigit.setForeground(new java.awt.Color(255, 255, 255));
        lblDigit.setText("* A digit");
        jPanel1.add(lblDigit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        lbl8Char2.setForeground(new java.awt.Color(255, 255, 255));
        lbl8Char2.setText("* At least 8 characters.");
        jPanel1.add(lbl8Char2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel8.setText("asddddddddddddddddddd");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 240, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/mycorona.png"))); // NOI18N
        jLabel1.setText("jnjn");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 360, 340));

        lblUpper1.setForeground(new java.awt.Color(255, 255, 255));
        lblUpper1.setText("* Upper case");
        jPanel1.add(lblUpper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:

        // lblClose.setBackground(Color.getColor("#04aa6d"));

    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setBackground(Color.RED);
    }//GEN-LAST:event_lblCloseMousePressed

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_txtUserMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:

        txtPassword.setText(null);
        txtPassword.setEchoChar('\u25cf');
        txtPassword.setForeground(Color.WHITE);

    }//GEN-LAST:event_txtPasswordMouseClicked

    private void lblInvisiblePsdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvisiblePsdMouseClicked
        // TODO add your handling code here:
        lblInvisiblePsd1.setVisible(false);
        lblVisiblePswd1.setVisible(true);
        txtPassword.setEchoChar('\u25cf');
    }//GEN-LAST:event_lblInvisiblePsdMouseClicked

    private void txtUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUser1MouseClicked
        // TODO add your handling code here:
        txtUser1.setForeground(Color.WHITE);
        txtUser1.setText(null);

    }//GEN-LAST:event_txtUser1MouseClicked

    private void txtPassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword1MouseClicked
        // TODO add your handling code here:

        txtPassword1.setText(null);
        txtPassword1.setEchoChar('\u25cf');
        txtPassword1.setForeground(Color.WHITE);

    }//GEN-LAST:event_txtPassword1MouseClicked

    private void lblInvisiblePsd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvisiblePsd1MouseClicked
        // TODO add your handling code here:
        lblInvisiblePsd1.setVisible(false);
        lblVisiblePswd1.setVisible(true);
        txtPassword2.setEchoChar('\u25cf');
    }//GEN-LAST:event_lblInvisiblePsd1MouseClicked

    private void txtPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword2MouseClicked
        // TODO add your handling code here:
        txtPassword2.setText(null);
        txtPassword2.setEchoChar('\u25cf');
        txtPassword2.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtPassword2MouseClicked

    private void lblVisiblePswd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisiblePswd1MouseClicked
        // TODO add your handling code here:

        lblVisiblePswd1.setVisible(false);
        lblInvisiblePsd1.setVisible(true);
        //visible the pswd
        txtPassword2.setEchoChar((char) 0);
    }//GEN-LAST:event_lblVisiblePswd1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Login obj = new Login();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String pass = txtPassword2.getText();
         String passCon = txtPassword1.getText();
         String uid = txtUser1.getText();
        
        char arr [] = pass.toCharArray();
        //password validation
       if(upperDon == false)
       {
           lblUpper.setForeground(Color.RED);
       }
       else
       {
          lblUpper.setForeground(Color.WHITE);
       }
       
        //password validation
       if(digitDon == false)
       {
           lblDigit.setForeground(Color.RED);
       }
       else
       {
          lblDigit.setForeground(Color.WHITE);
       }
       
       if(txtPassword2.getText().length() < 8)
       {
       lbl8Char2.setForeground(Color.RED);
       }
       else
       {
       lbl8Char2.setForeground(Color.WHITE);
       }
                  
        try{
        if(txtPassword2.getText().length() > 8 && (txtUser1.getText().isEmpty()) == false && (txtPassword1.getText().isEmpty()) == false && pass.equals(passCon) && upperDon == true && digitDon == true)
        {
          
          
            String query = "select id from userdetails where id = '" + uid + "';";
         
                st = con.createStatement();
                
               ResultSet rs = st.executeQuery(query);
              
               if(rs.next())
               {
                   if(rs.getString("id").equals(uid))
                   {
                        String query1 = "update userdetails set pass = '" + pass + "' where id = '" + uid + "';" ;
                        st.executeUpdate(query1);
                        
                        JOptionPane.showMessageDialog(this,"Password Updated!");
                        
                        Login obj = new Login();
                        obj.show();
                        this.dispose();
                   }
                   else
                   {
                       lblerror.setText("Invalid user id!");
                   }
               }
               else
               {
                   lblerror.setText("Please sign in first!");
               }
                
          
          
        }
        else
        {
            lblerror.setText("all fields are required*");
            
        }
        }
        catch(ArrayIndexOutOfBoundsException ee)
        {
             System.out.println(ee.toString());
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPassword2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassword2KeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtPassword2KeyPressed

    private void txtPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassword2KeyReleased
        // TODO add your handling code here:
          String pass = txtPassword2.getText();
        
        char arr [] = pass.toCharArray();
        //password validation
        for(int i = 0; i < arr.length; i++)
        {
            if(Character.isUpperCase(arr[i]))
            {
                lblUpper.setFont(new Font("Arial",Font.BOLD,12));
                upperDon = true;
            }
           
            
            if(Character.isDigit(arr[i]))
            {
                 lblDigit.setFont(new Font("Arial",Font.BOLD,12));
                 digitDon = true;
            }
          
      
        }
        
        if(arr.length > 8)
        {
            lbl8Char2.setFont(new Font("Arial",Font.BOLD,12));
        }
        
        if(arr.length == 0)
        {
            lbl8Char2.setFont(new Font("Arial",Font.PLAIN,12));
            lblDigit.setFont(new Font("Arial",Font.PLAIN,12));
            lblUpper.setFont(new Font("Arial",Font.PLAIN,12));
        }
    }//GEN-LAST:event_txtPassword2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl8Char2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDigit;
    private javax.swing.JLabel lblInvisiblePsd;
    private javax.swing.JLabel lblInvisiblePsd1;
    private javax.swing.JLabel lblUpper;
    private javax.swing.JLabel lblUpper1;
    private javax.swing.JLabel lblVisiblePswd1;
    private javax.swing.JLabel lblerror;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUser1;
    // End of variables declaration//GEN-END:variables
}
