/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covid19databank;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Random;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import conn.connection;
import java.net.URL;
import javax.swing.ImageIcon;




/**
 *
 * @author sasin
 */
public class signIn extends javax.swing.JFrame {

    /**
     * Creates new form signIn
     */
    
    //database detais
    
    private Statement st;
    private Connection con;
    
    
    public String gender;
    public int num;
    public String id;
    private String password;
    public int i = 0;
   
    
    public signIn() {
        
        this.setUndecorated(true);
        setResizable(false);
        initComponents();
        
         //set an icon
         URL image = getClass().getResource("/source/microbe_48px.png");
        ImageIcon img = new ImageIcon(image);
   
        this.setIconImage(img.getImage());
        
        //connection class
        con = connection.connect();
        

        
        //hide error messages
        hideErrorMessages();
        //hide verification email
        
        txtVerifyMail.setVisible(false);
        lblVerify.setVisible(false);
        sprtVerify.setVisible(false);
        
        //items of postion
       cmboPosition.addItem("Select your position");
        cmboPosition.addItem("Senior Doctor");
        cmboPosition.addItem("Junior Doctor");
         cmboPosition.addItem("Nurse");
          cmboPosition.addItem("Midwife");
           cmboPosition.addItem("Attendant");
            cmboPosition.addItem("Interns");
            
            buttonGroup1.add(rdoFemale);
            buttonGroup1.add(rdoMale);
            
           btnsignIn2.setVisible(false);
            
            lblTryError.setVisible(false);
            lblTryError1.setVisible(false);
            lblTryAgain.setVisible(false);
               sprtorTry.setVisible(false);
            
         
        
    }
    
    public void hideErrorMessages()
    {
        lblErrAddress.setVisible(false);
         lblErrBirthday.setVisible(false);
          lblErrEmail.setVisible(false);
           lblErrGender.setVisible(false);
            lblErrHospital.setVisible(false);
             lblErrId.setVisible(false);
              lblErrName.setVisible(false);
               lblErrPos.setVisible(false);
                lblErrTp.setVisible(false);
                
                errAddress.setVisible(false);
                errBirthday.setVisible(false);
                errGender.setVisible(false);
                errHospital.setVisible(false);
                errId.setVisible(false);
                errMail.setVisible(false);
                errName.setVisible(false);
                errPosition.setVisible(false);
                errTp.setVisible(false);
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNicError5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        lblVerify = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cmboPosition = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        nmbrWorkYear = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBOD = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnsignIn2 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtVerifyMail = new javax.swing.JTextField();
        sprtVerify = new javax.swing.JSeparator();
        errName = new javax.swing.JLabel();
        errAddress = new javax.swing.JLabel();
        errTp = new javax.swing.JLabel();
        errMail = new javax.swing.JLabel();
        errId = new javax.swing.JLabel();
        errGender = new javax.swing.JLabel();
        errPosition = new javax.swing.JLabel();
        errHospital = new javax.swing.JLabel();
        errBirthday = new javax.swing.JLabel();
        lblErrHospital = new javax.swing.JLabel();
        lblErrGender = new javax.swing.JLabel();
        lblErrEmail = new javax.swing.JLabel();
        lblErrName = new javax.swing.JLabel();
        lblErrTp = new javax.swing.JLabel();
        lblErrAddress = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblErrId = new javax.swing.JLabel();
        lblErrBirthday = new javax.swing.JLabel();
        lblErrPos = new javax.swing.JLabel();
        btnSignIn1 = new javax.swing.JButton();
        lblTryError = new javax.swing.JLabel();
        lblTryAgain = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sprtorTry = new javax.swing.JSeparator();
        lblTryError1 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        lblNicError5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNicError5.setForeground(new java.awt.Color(255, 0, 0));
        lblNicError5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNicError5.setText("x");
        lblNicError5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNicError5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNicError5MouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 170, 109));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("x");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 730, 670));

        lblClose.setBackground(new java.awt.Color(104, 170, 109));
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        lblMinimize.setBackground(new java.awt.Color(104, 170, 109));
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("_");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COVID 19 DATABANK");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 29));

        txtFullName.setBackground(new java.awt.Color(241, 241, 241));
        txtFullName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(153, 153, 153));
        txtFullName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFullName.setText("Enter your full name");
        txtFullName.setBorder(null);
        txtFullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFullNameMouseClicked(evt);
            }
        });
        txtFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFullNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 500, 34));

        txtAddress.setBackground(new java.awt.Color(241, 241, 241));
        txtAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(153, 153, 153));
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAddress.setText("Enter your address.");
        txtAddress.setBorder(null);
        txtAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddressMouseClicked(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 500, 34));

        txtTele.setBackground(new java.awt.Color(241, 241, 241));
        txtTele.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTele.setForeground(new java.awt.Color(153, 153, 153));
        txtTele.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTele.setText("Enter your tele no.");
        txtTele.setBorder(null);
        txtTele.setPreferredSize(new java.awt.Dimension(127, 17));
        txtTele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTeleMouseClicked(evt);
            }
        });
        txtTele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTeleKeyPressed(evt);
            }
        });
        jPanel1.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 500, 34));

        txtEmail.setBackground(new java.awt.Color(241, 241, 241));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.setText("Enter your e-mail.");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 500, 34));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("E-mail");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 425, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Telephone No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 425, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 425, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Full Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 425, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 232, 232));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATABANK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 349, 118, 29));

        txtEmail1.setBackground(new java.awt.Color(238, 234, 234));
        txtEmail1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail1.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail1.setText("Enter your e-mail.");
        txtEmail1.setBorder(null);
        txtEmail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmail1MouseClicked(evt);
            }
        });
        txtEmail1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmail1KeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 500, 34));

        lblVerify.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerify.setText("Verify ID");
        jPanel1.add(lblVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 720, 150, -1));

        txtHospital.setBackground(new java.awt.Color(241, 241, 241));
        txtHospital.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHospital.setForeground(new java.awt.Color(153, 153, 153));
        txtHospital.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtHospital.setText("Enter your current working hospital");
        txtHospital.setBorder(null);
        txtHospital.setPreferredSize(new java.awt.Dimension(127, 17));
        txtHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHospitalMouseClicked(evt);
            }
        });
        txtHospital.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalKeyPressed(evt);
            }
        });
        jPanel1.add(txtHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 500, 34));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Position");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 425, -1));

        txtId.setBackground(new java.awt.Color(241, 241, 241));
        txtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(153, 153, 153));
        txtId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtId.setText("Enter your id no.");
        txtId.setBorder(null);
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 500, 34));

        cmboPosition.setBackground(new java.awt.Color(241, 241, 241));
        cmboPosition.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(cmboPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 500, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("ID No.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 425, -1));

        rdoMale.setBackground(new java.awt.Color(255, 255, 255));
        rdoMale.setText("Male");
        jPanel1.add(rdoMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, -1, -1));

        rdoFemale.setBackground(new java.awt.Color(255, 255, 255));
        rdoFemale.setText("Female");
        rdoFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(rdoFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, -1, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 150, 90));

        nmbrWorkYear.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        nmbrWorkYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(nmbrWorkYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 110, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Hospital");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 425, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Working Years");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 110, -1));

        txtBOD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtBOD.setForeground(new java.awt.Color(204, 204, 204));
        txtBOD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBOD.setText("dd /  mm /  yyyy");
        txtBOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBODMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBODMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBODMouseExited(evt);
            }
        });
        txtBOD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBODKeyPressed(evt);
            }
        });
        jPanel1.add(txtBOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 180, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(4, 170, 104));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SIGN IN");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 720, 50));

        btnCancel.setBackground(new java.awt.Color(51, 51, 51));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, 120, 30));

        btnsignIn2.setBackground(new java.awt.Color(4, 170, 104));
        btnsignIn2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnsignIn2.setForeground(new java.awt.Color(255, 255, 255));
        btnsignIn2.setText("Sign In");
        btnsignIn2.setBorder(null);
        btnsignIn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsignIn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsignIn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsignIn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsignIn2MouseExited(evt);
            }
        });
        btnsignIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignIn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsignIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 790, 290, 30));

        btnClear.setBackground(new java.awt.Color(51, 51, 51));
        btnClear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(null);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 790, 120, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Birthday");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 60, -1));

        txtVerifyMail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtVerifyMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVerifyMail.setBorder(null);
        txtVerifyMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVerifyMailMouseClicked(evt);
            }
        });
        jPanel1.add(txtVerifyMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 740, 160, -1));

        sprtVerify.setForeground(new java.awt.Color(4, 170, 109));
        jPanel1.add(sprtVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 760, 160, 30));

        errName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errName.setForeground(new java.awt.Color(255, 0, 0));
        errName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errName.setText("x");
        errName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errNameMouseExited(evt);
            }
        });
        jPanel1.add(errName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 20, 30));

        errAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errAddress.setForeground(new java.awt.Color(255, 0, 0));
        errAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errAddress.setText("x");
        errAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errAddressMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errAddressMouseExited(evt);
            }
        });
        jPanel1.add(errAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 20, 30));

        errTp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errTp.setForeground(new java.awt.Color(255, 0, 0));
        errTp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errTp.setText("x");
        errTp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errTpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errTpMouseExited(evt);
            }
        });
        jPanel1.add(errTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 20, 30));

        errMail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errMail.setForeground(new java.awt.Color(255, 0, 0));
        errMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errMail.setText("x");
        errMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errMailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errMailMouseExited(evt);
            }
        });
        jPanel1.add(errMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 20, 30));

        errId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errId.setForeground(new java.awt.Color(255, 0, 0));
        errId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errId.setText("x");
        errId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errIdMouseExited(evt);
            }
        });
        jPanel1.add(errId, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 20, 30));

        errGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errGender.setForeground(new java.awt.Color(255, 0, 0));
        errGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errGender.setText("x");
        errGender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errGenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errGenderMouseExited(evt);
            }
        });
        jPanel1.add(errGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, 20, 30));

        errPosition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errPosition.setForeground(new java.awt.Color(255, 0, 0));
        errPosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errPosition.setText("x");
        errPosition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errPositionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errPositionMouseExited(evt);
            }
        });
        jPanel1.add(errPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 20, 30));

        errHospital.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errHospital.setForeground(new java.awt.Color(255, 0, 0));
        errHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errHospital.setText("x");
        errHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errHospitalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errHospitalMouseExited(evt);
            }
        });
        jPanel1.add(errHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 20, 30));

        errBirthday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errBirthday.setForeground(new java.awt.Color(255, 0, 0));
        errBirthday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errBirthday.setText("x");
        errBirthday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                errBirthdayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                errBirthdayMouseExited(evt);
            }
        });
        jPanel1.add(errBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 20, 30));

        lblErrHospital.setBackground(new java.awt.Color(0, 0, 0));
        lblErrHospital.setForeground(new java.awt.Color(255, 255, 255));
        lblErrHospital.setText("Please enter your hospital!");
        lblErrHospital.setOpaque(true);
        jPanel1.add(lblErrHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 150, -1));

        lblErrGender.setBackground(new java.awt.Color(0, 0, 0));
        lblErrGender.setForeground(new java.awt.Color(255, 255, 255));
        lblErrGender.setText("Please select your gender!");
        lblErrGender.setOpaque(true);
        jPanel1.add(lblErrGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 140, -1));

        lblErrEmail.setBackground(new java.awt.Color(0, 0, 0));
        lblErrEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblErrEmail.setText("Please enter your e-mail!");
        lblErrEmail.setOpaque(true);
        jPanel1.add(lblErrEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 140, -1));

        lblErrName.setBackground(new java.awt.Color(0, 0, 0));
        lblErrName.setForeground(new java.awt.Color(255, 255, 255));
        lblErrName.setText("Please enter your full name!");
        lblErrName.setOpaque(true);
        jPanel1.add(lblErrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 150, -1));

        lblErrTp.setBackground(new java.awt.Color(0, 0, 0));
        lblErrTp.setForeground(new java.awt.Color(255, 255, 255));
        lblErrTp.setText("Please enter your Tele.No.!");
        lblErrTp.setOpaque(true);
        jPanel1.add(lblErrTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 140, -1));

        lblErrAddress.setBackground(new java.awt.Color(0, 0, 0));
        lblErrAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblErrAddress.setText("Please enter your address!");
        lblErrAddress.setOpaque(true);
        jPanel1.add(lblErrAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 150, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/thiaaa.png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 720, 310));

        lblErrId.setBackground(new java.awt.Color(0, 0, 0));
        lblErrId.setForeground(new java.awt.Color(255, 255, 255));
        lblErrId.setText("Please enter your id no.!");
        lblErrId.setOpaque(true);
        jPanel1.add(lblErrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 130, -1));

        lblErrBirthday.setBackground(new java.awt.Color(0, 0, 0));
        lblErrBirthday.setForeground(new java.awt.Color(255, 255, 255));
        lblErrBirthday.setText("Please enter your birthday!");
        lblErrBirthday.setOpaque(true);
        jPanel1.add(lblErrBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 150, -1));

        lblErrPos.setBackground(new java.awt.Color(0, 0, 0));
        lblErrPos.setForeground(new java.awt.Color(255, 255, 255));
        lblErrPos.setText("Please select your position!");
        lblErrPos.setOpaque(true);
        jPanel1.add(lblErrPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 150, -1));

        btnSignIn1.setBackground(new java.awt.Color(4, 170, 104));
        btnSignIn1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSignIn1.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn1.setText("Verify ID");
        btnSignIn1.setBorder(null);
        btnSignIn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignIn1MouseClicked(evt);
            }
        });
        btnSignIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignIn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 790, 290, 30));

        lblTryError.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblTryError.setForeground(new java.awt.Color(255, 0, 0));
        lblTryError.setText("only 3 times you can try.");
        jPanel1.add(lblTryError, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 740, -1, -1));

        lblTryAgain.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTryAgain.setForeground(new java.awt.Color(0, 51, 204));
        lblTryAgain.setText("try again.");
        lblTryAgain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTryAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTryAgainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTryAgainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTryAgainMouseExited(evt);
            }
        });
        jPanel1.add(lblTryAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 720, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 730, -1, -1));

        sprtorTry.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(sprtorTry, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 740, 50, 20));

        lblTryError1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblTryError1.setForeground(new java.awt.Color(255, 0, 0));
        lblTryError1.setText("Your ID is not matching please ");
        jPanel1.add(lblTryError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 720, -1, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/DATABANK.png"))); // NOI18N
        lblBack.setToolTipText("");
        lblBack.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -30, 780, 890));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:

        // lblClose.setBackground(Color.getColor("#04aa6d"));

    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setBackground(Color.RED);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(signIn.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void txtEmail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmail1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1MouseClicked

    private void txtEmail1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmail1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1KeyPressed

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
        // TODO add your handling code here:
         txtId.setText(null);
        txtId.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtIdMouseClicked

    private void rdoFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoFemaleActionPerformed

    private void errNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errNameMouseEntered
        // TODO add your handling code here:

        lblErrName.setVisible(true);
    }//GEN-LAST:event_errNameMouseEntered

    private void errNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errNameMouseExited
        // TODO add your handling code here:

        lblErrName.setVisible(false);
    }//GEN-LAST:event_errNameMouseExited

    private void errAddressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errAddressMouseEntered

        lblErrAddress.setVisible(true);
    }//GEN-LAST:event_errAddressMouseEntered

    private void errAddressMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errAddressMouseExited
        lblErrAddress.setVisible(false);
    }//GEN-LAST:event_errAddressMouseExited

    private void errTpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errTpMouseEntered
        lblErrTp.setVisible(true);
    }//GEN-LAST:event_errTpMouseEntered

    private void errTpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errTpMouseExited
        lblErrTp.setVisible(false);
    }//GEN-LAST:event_errTpMouseExited

    private void errMailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errMailMouseEntered
        lblErrEmail.setVisible(true);
    }//GEN-LAST:event_errMailMouseEntered

    private void errMailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errMailMouseExited
        lblErrEmail.setVisible(false);
    }//GEN-LAST:event_errMailMouseExited

    private void errIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errIdMouseEntered
        lblErrId.setVisible(true);
    }//GEN-LAST:event_errIdMouseEntered

    private void errIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errIdMouseExited
        lblErrId.setVisible(false);
    }//GEN-LAST:event_errIdMouseExited

    private void errGenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errGenderMouseEntered
        lblErrGender.setVisible(true);
    }//GEN-LAST:event_errGenderMouseEntered

    private void errGenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errGenderMouseExited
        lblErrGender.setVisible(false);
    }//GEN-LAST:event_errGenderMouseExited

    private void errPositionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errPositionMouseEntered
        // TODO add your handling code here:
        lblErrPos.setVisible(true);
    }//GEN-LAST:event_errPositionMouseEntered

    private void errPositionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errPositionMouseExited
        // TODO add your handling code here:
         lblErrPos.setVisible(false);
    }//GEN-LAST:event_errPositionMouseExited

    private void errHospitalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errHospitalMouseEntered
        // TODO add your handling code here:
        lblErrHospital.setVisible(true);
    }//GEN-LAST:event_errHospitalMouseEntered

    private void errHospitalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errHospitalMouseExited
        // TODO add your handling code here:
        lblErrHospital.setVisible(true);
    }//GEN-LAST:event_errHospitalMouseExited

    private void errBirthdayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errBirthdayMouseEntered
        // TODO add your handling code here:
        lblErrBirthday.setVisible(true);
        lblErrBirthday.setText("Please enter your birthday!");
    }//GEN-LAST:event_errBirthdayMouseEntered

    private void errBirthdayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_errBirthdayMouseExited
        // TODO add your handling code here:
         lblErrBirthday.setVisible(false);
    }//GEN-LAST:event_errBirthdayMouseExited

    private void lblNicError5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNicError5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNicError5MouseEntered

    private void lblNicError5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNicError5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNicError5MouseExited

    private void txtFullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullNameKeyPressed
        // TODO add your handling code here:
        
        if(txtFullName.getText().length() < 4)
        {
            
            errName.setVisible(true);
        }
        else
        {
            errName.setVisible(false);
        }
    }//GEN-LAST:event_txtFullNameKeyPressed

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
        // TODO add your handling code here:
       
        if(txtAddress.getText().length() < 4)
        {
            errAddress.setVisible(true);
        }
        else
        {
            errAddress.setVisible(false);
        }
        
    }//GEN-LAST:event_txtAddressKeyPressed

    private void txtFullNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFullNameMouseClicked
        // TODO add your handling code here:
        
        txtFullName.setText(null);
        txtFullName.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtFullNameMouseClicked

    private void txtAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddressMouseClicked
        // TODO add your handling code here:
         txtAddress.setText(null);
        txtAddress.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtAddressMouseClicked

    private void txtTeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTeleMouseClicked
        // TODO add your handling code here:
         txtTele.setText(null);
        txtTele.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTeleMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
         txtEmail.setText(null);
        txtEmail.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHospitalMouseClicked
        // TODO add your handling code here:
         txtHospital.setText(null);
        txtHospital.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtHospitalMouseClicked

    private void txtBODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBODMouseClicked
        // TODO add your handling code here:
         txtBOD.setText(null);
        txtBOD.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_txtBODMouseClicked

    private void txtBODKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBODKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c) || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_SLASH)
        {
            txtBOD.setEditable(true);
        }
        else
        {
            txtBOD.setEditable(false);
        }
        
        if(txtBOD.getText().length() < 9)
        {
            errBirthday.setVisible(true);
        }
        else
        {
            errBirthday.setVisible(false);
        }
    }//GEN-LAST:event_txtBODKeyPressed

    private void txtBODMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBODMouseEntered
        // TODO add your handling code here:
        
        lblErrBirthday.setVisible(true);
        lblErrBirthday.setText("dd/mm/yyyy");
    }//GEN-LAST:event_txtBODMouseEntered

    private void txtBODMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBODMouseExited
        // TODO add your handling code here:
            lblErrBirthday.setVisible(false);
        lblErrBirthday.setText("Please enter your birthday!");
    }//GEN-LAST:event_txtBODMouseExited

    private void txtTeleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c) || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
        {
            txtTele.setEditable(true);
        }
        else
        {
            txtTele.setEditable(false);
        }
        if(txtTele.getText().length() < 9 || txtTele.getText().length() > 9)
        {
            errTp.setVisible(true);
        }
        else
        {
            errTp.setVisible(false);
        }
    }//GEN-LAST:event_txtTeleKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        
    
        
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtEmail.getText());
        
        if(!match.matches())
        {
            errMail.setVisible(true);
        }
        else
        {
            errMail.setVisible(false);
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        // TODO add your handling code here:
        
        if(txtId.getText().length() > 11 || txtId.getText().length() < 9)
        {
            errId.setVisible(true);
        }
        else
        {
            errId.setVisible(false);
        }
        if(txtId.getText().length() == 8)
        {
            lblErrId.setVisible(true);
            lblErrId.setText("eneter capital 'V' ");
        }
        else
        {
            lblErrId.setVisible(false);
            lblErrId.setText("Please enter your id!");
        }
        
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_V)
        {
            txtId.setEditable(true);
        }
        else
        {
            txtId.setEditable(false);
        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtHospitalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalKeyPressed
        // TODO add your handling code here:
        if(txtHospital.getText().length() < 3)
        {
            errHospital.setVisible(true);
        }
        else
        {
            errHospital.setVisible(false);
        }
    }//GEN-LAST:event_txtHospitalKeyPressed

    public void emptyBoxValidate()
    {
        if(txtAddress.getText().isEmpty())
        {
            errAddress.setVisible(true);
        }
        else
        {
            errAddress.setVisible(false);
        }
        
        if(txtBOD.getText().isEmpty())
        {
            errBirthday.setVisible(true);
        }
        else
        {
            errBirthday.setVisible(false);
        }
        
        if(txtFullName.getText().isEmpty())
        {
            errName.setVisible(true);
        }
        else
        {
            errName.setVisible(false);
        }
        
        if(txtEmail.getText().isEmpty())
        {
            errMail.setVisible(true);
        }
        else
        {
            errMail.setVisible(false);
        }
        
        if(txtHospital.getText().isEmpty())
        {
            errHospital.setVisible(true);
        }
        else
        {
            errHospital.setVisible(false);
        }
        
        if(txtId.getText().isEmpty())
        {
            errId.setVisible(true);
        }
        else
        {
            errId.setVisible(false);
        }
        
        
         if(txtTele.getText().isEmpty())
        {
            errTp.setVisible(true);
        }
        else
        {
            errTp.setVisible(false);
        }
         
      
    }
    
    private void btnsignIn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignIn2MouseClicked
        // TODO add your handling code here:
      
       
        
        
        
      
    }//GEN-LAST:event_btnsignIn2MouseClicked

    private void btnSignIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignIn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignIn1MouseClicked

    private void getGender()
    {
        if(rdoMale.isSelected())
        {
            gender = "Male";
        }
        else
        {
            gender = "female";
        }
    }
    
    private void btnsignIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignIn2ActionPerformed
        // TODO add your handling code here:
    
        
        //get gender
        getGender();
        if(id.equals(txtVerifyMail.getText()))
        {
            try{
                //get random password
                Random rnd = new Random();
            
                 num = rnd.nextInt(199999);
                 password = "P@#p" + Integer.toString(num);
             
                String name = txtFullName.getText();
                String address = txtAddress.getText();
                int tele = Integer.parseInt(txtTele.getText());
                String mail = txtEmail.getText();
                String idno = txtId.getText();
                String position = cmboPosition.getSelectedItem().toString();
                String hospital = txtHospital.getText();
                String birth = txtBOD.getText();
                int years = (int) nmbrWorkYear.getValue();
                
                
                //mysql query to insert data
                String query = "insert into userdetails values('" + id + "','" + name + "','" + address + "','" + tele + "','" + mail
                        + "','" + idno + "','" + position + "','" + hospital + "','" + gender + "','" + birth + "'," + years + ",'" + password +"');";
                
                st = con.createStatement();
                
                st.executeUpdate(query);
                
                 con.close();
                 st.close();
                 
            JOptionPane.showMessageDialog(this,"Please remember your password: " + password,"Sign In",JOptionPane.INFORMATION_MESSAGE);     
                   
            JOptionPane.showMessageDialog(this,"Signed in successfully","Sign In",JOptionPane.INFORMATION_MESSAGE);
             Login obj = new Login();
            obj.show();
            
            this.dispose();
                
            }
            catch(ArithmeticException ee)
            {
                System.out.println(ee.toString());
            }
            catch(Exception e)
            {
                System.out.println(e.toString());
            }
          
        
        }
        else
        {
            lblTryAgain.setVisible(true);
            lblTryError.setVisible(true);
             lblTryError1.setVisible(true);
        }
        
       
        
    }//GEN-LAST:event_btnsignIn2ActionPerformed

    private void btnSignIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignIn1ActionPerformed
        // TODO add your handling code here:
        
          emptyBoxValidate(); //empty textboxes validate
       //postion validate
        if(cmboPosition.getSelectedIndex() == 0)
        {
            errPosition.setVisible(true);
        }
        else
        {
            errPosition.setVisible(false);
        }
        //validate gender
        if(rdoFemale.isSelected() == false && rdoMale.isSelected() == false)
        {
            errGender.setVisible(true);
        }
        else
        {
            errGender.setVisible(false);
        }
        
        //if there are no errors send the verification code to email
        if(errAddress.isVisible() == false && errBirthday.isVisible() == false && errGender.isVisible() == false && errHospital.isVisible() == false && errId.isVisible() == false && errMail.isVisible() == false &&
                
                errMail.isVisible() == false && errName.isVisible() == false && errPosition.isVisible() == false && errTp.isVisible() == false)
        {
            
          
            Random rnd = new Random();
            
            num = rnd.nextInt(10000);
            id = "D" + Integer.toString(num);
            JOptionPane.showMessageDialog(this,id,"Your verification code",JOptionPane.INFORMATION_MESSAGE);
            
            lblVerify.setVisible(true);
            txtVerifyMail.setVisible(true);
            sprtVerify.setVisible(true);
            
            btnsignIn2.setVisible(true);
            btnSignIn1.setVisible(false);
            
            btnCancel.setEnabled(false);
            btnClear.setEnabled(false);
            
            
            //text boxes disable after get ID
            txtAddress.setEnabled(false);
             txtBOD.setEnabled(false);
              txtEmail.setEnabled(false);
               txtFullName.setEnabled(false);
                txtHospital.setEnabled(false);
                 txtId.setEnabled(false);
                  txtTele.setEnabled(false);
                  cmboPosition.setEnabled(false);
                  nmbrWorkYear.setEnabled(false);
                  rdoFemale.setEnabled(false);
                  rdoMale.setEnabled(false);
                  
            
           
            
            
        }
        
        
 
    }//GEN-LAST:event_btnSignIn1ActionPerformed

    private void lblTryAgainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTryAgainMouseClicked
        // TODO add your handling code here:
       
        i++;
        
        //security restriction
        if(i == 3)
        {
            JOptionPane.showMessageDialog(this,"Security Restrictions!","Sign In",JOptionPane.WARNING_MESSAGE);
            Login obj = new Login();
            obj.show();
            this.dispose();
        }
        else
        {
            //genarate id
        Random rnd = new Random();
            
            num = rnd.nextInt(10000);
            id = "D" + Integer.toString(num);
            JOptionPane.showMessageDialog(this,id,"Your verification code",JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_lblTryAgainMouseClicked

    private void txtVerifyMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVerifyMailMouseClicked
        // TODO add your handling code here:
        
        txtVerifyMail.setText(null);
    }//GEN-LAST:event_txtVerifyMailMouseClicked

    private void lblTryAgainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTryAgainMouseEntered
        // TODO add your handling code here:
        sprtorTry.setVisible(true);
        lblTryAgain.setFont(new Font("Arial",Font.BOLD,14));
        
    }//GEN-LAST:event_lblTryAgainMouseEntered

    private void lblTryAgainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTryAgainMouseExited
        // TODO add your handling code here:
           sprtorTry.setVisible(false);
           lblTryAgain.setFont(new Font("Arial",Font.ITALIC,12));
    }//GEN-LAST:event_lblTryAgainMouseExited

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        Login obj = new Login();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
          txtAddress.setText(null);
             txtBOD.setText(null);
              txtEmail.setText(null);
               txtFullName.setText(null);
                txtHospital.setText(null);
                 txtId.setText(null);
                  txtTele.setText(null);
                  cmboPosition.setSelectedIndex(0);
                  
                 
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnsignIn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignIn2MouseEntered
        // TODO add your handling code here:
        btnsignIn2.setFont(new Font("Arial",Font.BOLD,19));
    }//GEN-LAST:event_btnsignIn2MouseEntered

    private void btnsignIn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignIn2MouseExited
        // TODO add your handling code here:
         btnsignIn2.setFont(new Font("Arial",Font.BOLD,18));
    }//GEN-LAST:event_btnsignIn2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSignIn1;
    private javax.swing.JButton btnsignIn2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmboPosition;
    private javax.swing.JLabel errAddress;
    private javax.swing.JLabel errBirthday;
    private javax.swing.JLabel errGender;
    private javax.swing.JLabel errHospital;
    private javax.swing.JLabel errId;
    private javax.swing.JLabel errMail;
    private javax.swing.JLabel errName;
    private javax.swing.JLabel errPosition;
    private javax.swing.JLabel errTp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblErrAddress;
    private javax.swing.JLabel lblErrBirthday;
    private javax.swing.JLabel lblErrEmail;
    private javax.swing.JLabel lblErrGender;
    private javax.swing.JLabel lblErrHospital;
    private javax.swing.JLabel lblErrId;
    private javax.swing.JLabel lblErrName;
    private javax.swing.JLabel lblErrPos;
    private javax.swing.JLabel lblErrTp;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblNicError5;
    private javax.swing.JLabel lblTryAgain;
    private javax.swing.JLabel lblTryError;
    private javax.swing.JLabel lblTryError1;
    private javax.swing.JLabel lblVerify;
    private javax.swing.JSpinner nmbrWorkYear;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JSeparator sprtVerify;
    private javax.swing.JSeparator sprtorTry;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBOD;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTele;
    private javax.swing.JTextField txtVerifyMail;
    // End of variables declaration//GEN-END:variables
}
