/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covid19databank;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import conn.connection;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.io.Writer;
import java.io.*;
import conn.vaccinedPData;
import java.net.URL;
import javax.swing.ImageIcon;
/**
 *
 * @author sasin0
 */
public class vaccinedPersons extends javax.swing.JFrame {

    /**
     * Creates new form vaccinedPersons
     */
    Connection con;
    Statement st;
    public vaccinedPersons() {
        this.setUndecorated(true);
        setResizable(false);
        initComponents();
        
         //set an icon
         URL image = getClass().getResource("/source/microbe_48px.png");
        ImageIcon img = new ImageIcon(image);
   
        this.setIconImage(img.getImage());
        
        con = connection.connect();
        st = null;
        
        //table details
        tableDetail();
        
        //get data to table
        getData();
        
         pnlCovidAffect.setVisible(false);
    }
    
    public void tableDetail()
    {
        tblVaccinedPerson.getTableHeader().setFont(new Font("Arial",Font.BOLD,14));
         tblVaccinedPerson.getTableHeader().setOpaque(false);
         tblVaccinedPerson.getTableHeader().setBackground(new Color(4,170,109));
          tblVaccinedPerson.getTableHeader().setForeground(new Color(255,255,255));
          tblVaccinedPerson.setRowHeight(25);
          
        
        
    }
    
    public void getData()
    {
     
        try{
        
            //call vaccine data method 
              vaccinedPData.count();
              //get vaccined person count from it
             lbltotalVP.setText("TOTAL VACCINED PERSONS: " + vaccinedPData.COUNT);
            
            //create statement
            st = con.createStatement();
           
            //get all vaccined persons details
            String query = "select * from addvacc;";
            
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next())
            {
                String nic = rs.getString("nic");
                String name = rs.getString("name");
                String age = Integer.toString(rs.getInt("age"));
                String vacc1 = rs.getString("1stVac");
                String vacc2 = rs.getString("2ndVac");
                String booster = rs.getString("booster");
                
                String tbData[] = {nic,name,age,vacc1,vacc2,booster};
                
                DefaultTableModel tblModel = (DefaultTableModel)tblVaccinedPerson.getModel();
                
                tblModel.addRow(tbData);
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        pnlCovidAffect = new javax.swing.JPanel();
        txtAffectedDate = new javax.swing.JTextField();
        txtReportCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAffected = new javax.swing.JButton();
        lblAffectedPName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccinedPerson = new javax.swing.JTable();
        lbltotalVP = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnCovidAffect1 = new javax.swing.JButton();

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(4, 170, 104));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ADD VACCINES");

        btnLogout.setBackground(new java.awt.Color(4, 170, 109));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log Out");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(4, 170, 109));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 820, 10));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(4, 170, 104));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("VACCINED PERSONS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 60));

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setForeground(new java.awt.Color(255, 0, 0));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 20));

        lblMinimize.setBackground(new java.awt.Color(255, 255, 255));
        lblMinimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(4, 170, 109));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 20));

        pnlCovidAffect.setBackground(new java.awt.Color(255, 255, 255));
        pnlCovidAffect.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAffectedDate.setBackground(new java.awt.Color(244, 244, 244));
        txtAffectedDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAffectedDate.setForeground(new java.awt.Color(204, 204, 204));
        txtAffectedDate.setText("Enter covid affected date");
        txtAffectedDate.setBorder(null);
        txtAffectedDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAffectedDateMouseClicked(evt);
            }
        });
        pnlCovidAffect.add(txtAffectedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 246, 30));

        txtReportCode.setBackground(new java.awt.Color(244, 244, 244));
        txtReportCode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtReportCode.setForeground(new java.awt.Color(204, 204, 204));
        txtReportCode.setText("Enter Report Code");
        txtReportCode.setBorder(null);
        txtReportCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReportCodeMouseClicked(evt);
            }
        });
        pnlCovidAffect.add(txtReportCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 246, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 170, 109));
        jLabel3.setText("Date:");
        pnlCovidAffect.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(4, 170, 109));
        jLabel4.setText("PCR or Antigen Report Code :");
        pnlCovidAffect.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        pnlCovidAffect.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        btnAffected.setBackground(new java.awt.Color(255, 102, 102));
        btnAffected.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAffected.setForeground(new java.awt.Color(255, 255, 255));
        btnAffected.setText("Affected");
        btnAffected.setBorder(null);
        btnAffected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAffected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAffectedActionPerformed(evt);
            }
        });
        pnlCovidAffect.add(btnAffected, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 80, 30));

        lblAffectedPName.setBackground(new java.awt.Color(255, 255, 255));
        lblAffectedPName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblAffectedPName.setForeground(new java.awt.Color(4, 170, 104));
        lblAffectedPName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAffectedPName.setText("VACCINED PERSONS");
        pnlCovidAffect.add(lblAffectedPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 510, 40));

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 255, 153))); // NOI18N
        pnlCovidAffect.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 510, 270));

        jPanel1.add(pnlCovidAffect, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 760, 410));

        txtSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(204, 204, 204));
        txtSearch.setText("Search by NIC");
        txtSearch.setBorder(null);
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, -1));

        jSeparator1.setForeground(new java.awt.Color(4, 170, 109));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 20));

        jLabel2.setBackground(new java.awt.Color(4, 170, 109));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 29, 530, 23));

        jScrollPane1.setBackground(new java.awt.Color(4, 170, 109));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblVaccinedPerson.setAutoCreateRowSorter(true);
        tblVaccinedPerson.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblVaccinedPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Name", "Age", "1st Vaccine", "2nd Vaccine", "Booster"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVaccinedPerson.setFocusable(false);
        tblVaccinedPerson.setGridColor(new java.awt.Color(255, 255, 255));
        tblVaccinedPerson.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblVaccinedPerson.setRowHeight(25);
        tblVaccinedPerson.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tblVaccinedPerson.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblVaccinedPerson.setShowVerticalLines(false);
        tblVaccinedPerson.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblVaccinedPerson);
        if (tblVaccinedPerson.getColumnModel().getColumnCount() > 0) {
            tblVaccinedPerson.getColumnModel().getColumn(0).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(1).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(2).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(3).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(4).setResizable(false);
            tblVaccinedPerson.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 760, 280));

        lbltotalVP.setBackground(new java.awt.Color(153, 153, 153));
        lbltotalVP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltotalVP.setForeground(new java.awt.Color(255, 28, 47));
        lbltotalVP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltotalVP.setText("TOTAL VACCINED PERSONS");
        jPanel1.add(lbltotalVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 390, -1));

        btnBack.setBackground(new java.awt.Color(4, 170, 109));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 100, 30));

        btnReport.setBackground(new java.awt.Color(255, 255, 255));
        btnReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/download_graph_report_32px.png"))); // NOI18N
        btnReport.setBorder(null);
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 40, 30));

        btnDelete.setBackground(new java.awt.Color(4, 170, 109));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 100, 30));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/search_24px.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 30, 30));

        btnCovidAffect1.setBackground(new java.awt.Color(4, 170, 109));
        btnCovidAffect1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCovidAffect1.setForeground(new java.awt.Color(255, 255, 255));
        btnCovidAffect1.setText("Covid Affect");
        btnCovidAffect1.setBorder(null);
        btnCovidAffect1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCovidAffect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCovidAffect1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCovidAffect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:

        // lblClose.setBackground(Color.getColor("#04aa6d"));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setBackground(Color.RED);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(home.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:

        Login obj = new Login();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        home obj = new home();
        obj.show();
        this.dispose();
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
            //file saving path
            File file = new File("VaccinedPersons.txt");
            
     
            try{
                //make a new file
                FileWriter fw = new FileWriter(file);
                BufferedWriter bw = new BufferedWriter(fw);
               fw.write("---Covid Vaccined Persons List----");
                fw.write("\n\n");
            
                fw.write("NIC   |   NAME   |  AGE  |  1st Vaccine  | 1st Vaccine | BOOSTER\n");
              
                bw.newLine();
                bw.newLine();
                
                for(int i = 0; i < tblVaccinedPerson.getRowCount(); i++){//rows
              
                    for(int j = 0; j < tblVaccinedPerson.getColumnCount(); j++){//columns
                    
                        bw.write("| " + tblVaccinedPerson.getValueAt(i,j).toString() + "\t" );
                        
                    }
                    bw.newLine();
                }
                
                bw.close();
                fw.close();
                
                JOptionPane.showMessageDialog(this, "Report has been genareted!","report",JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException e)
            {
                System.out.println(e.toString());
            }
            catch(Exception ee)
            {
                System.out.println(ee.toString());
            }
            
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        try{
        
            int row = tblVaccinedPerson.getSelectedRow();
            String cell = tblVaccinedPerson.getModel().getValueAt(row,0).toString();
            String query = "delete from addvacc where nic = '" + cell + "'";
            
            st = con.createStatement();
            
            int d =  JOptionPane.showConfirmDialog(this,"delete","Do you want to delete this data?",JOptionPane.WARNING_MESSAGE);
            
            if(d == 0)
            {
               st.executeUpdate(query);
              //clear table
              tblVaccinedPerson.setModel(new DefaultTableModel(null,new String [] {"NIC","name","Age","1st Vaccine","2nd Vaccine","Booster"}));
               getData();
               
            }
            
        }
        catch(Exception e)
        {
           System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
          try{
        
            //create statement
            st = con.createStatement();
            
            String search = txtSearch.getText();
            
            
            //get all vaccined persons details
            String query = "select * from addvacc where nic like '" + search +"%';";
            
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next())
            {
                tblVaccinedPerson.setModel(new DefaultTableModel(null,new String [] {"NIC","name","Age","1st Vaccine","2nd Vaccine","Booster"}));
                String nic = rs.getString("nic");
                String name = rs.getString("name");
                String age = Integer.toString(rs.getInt("age"));
                String vacc1 = rs.getString("1stVac");
                String vacc2 = rs.getString("2ndVac");
                String booster = rs.getString("booster");
                
                String tbData[] = {nic,name,age,vacc1,vacc2,booster};
                
                DefaultTableModel tblModel = (DefaultTableModel)tblVaccinedPerson.getModel();
                
                tblModel.addRow(tbData);
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCovidAffect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCovidAffect1ActionPerformed
        // TODO add your handling code here:
        pnlCovidAffect.setVisible(true);
        tblVaccinedPerson.setVisible(false);
        jScrollPane1.setVisible(false);
        btnCovidAffect1.setVisible(false);
        btnDelete.setVisible(false);
        try{
            //get the selected row and cell
         int row = tblVaccinedPerson.getSelectedRow();
        String cell = tblVaccinedPerson.getModel().getValueAt(row,0).toString();
        
                 st = con.createStatement();
                //check whether the person is current covid patient or not
                String query2 = "select nic from affected where nic = '" + cell + "'";
                
                ResultSet rs = st.executeQuery(query2);
                
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(this, "This person is current covid \naffected patient!","warning",JOptionPane.WARNING_MESSAGE);
                       pnlCovidAffect.setVisible(false);
                       tblVaccinedPerson.setVisible(true);
                       jScrollPane1.setVisible(true);
                       btnCovidAffect1.setVisible(true);
                       btnDelete.setVisible(true);
                }
                else
                {
                    lblAffectedPName.setText(cell);
                    
                     pnlCovidAffect.setVisible(true);
                     tblVaccinedPerson.setVisible(false);
                     jScrollPane1.setVisible(false);
                     btnCovidAffect1.setVisible(false);
                     btnDelete.setVisible(false);
                }
       
        
        }
        catch(ArrayIndexOutOfBoundsException ee)
        {
            JOptionPane.showMessageDialog(this,"Please Select A Patient!","empty",JOptionPane.ERROR_MESSAGE);
                       pnlCovidAffect.setVisible(false);
                       tblVaccinedPerson.setVisible(true);
                       jScrollPane1.setVisible(true);
                       btnCovidAffect1.setVisible(true);
                       btnDelete.setVisible(true);
        
         
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
        
    }//GEN-LAST:event_btnCovidAffect1ActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
        txtSearch.setText(null);
        txtSearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtAffectedDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAffectedDateMouseClicked
        // TODO add your handling code here:

        txtAffectedDate.setText(null);
        txtAffectedDate.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtAffectedDateMouseClicked

    private void txtReportCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReportCodeMouseClicked
        // TODO add your handling code here:
        txtReportCode.setText(null);
        txtReportCode.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtReportCodeMouseClicked

    private void btnAffectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAffectedActionPerformed
        // TODO add your handling code here:
        if(txtAffectedDate.getText().isEmpty() | txtReportCode.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter report code and date!","empty",JOptionPane.ERROR_MESSAGE);
        }
        else{
        
            try{
                int row = tblVaccinedPerson.getSelectedRow();
                
                String report = txtReportCode.getText();
                String day = txtAffectedDate.getText();
                String cell = tblVaccinedPerson.getModel().getValueAt(row,0).toString();
                st = con.createStatement();
                
                String query2 = "select nic from affected where nic = '" + cell + "'";
                
                ResultSet rs = st.executeQuery(query2);
                
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(this, "This person is current covid \naffected patient!","warning",JOptionPane.WARNING_MESSAGE);
                }
                else{
                String query = "insert into affected(nic,reportNo,day) values('" + cell + "','" + report + "','" + day + "');";
                st.executeUpdate(query);
                
                //update addvacc table as covid affected
                String query1 =  "update addvacc set covidAffect = 'yes' where nic = '" + cell + "';";
                st.executeUpdate(query1);
                
                JOptionPane.showMessageDialog(this, "Covid 19 Affected Patient Updated!","add",JOptionPane.INFORMATION_MESSAGE);
                
                }
                
                
                
                
            }catch(Exception e)
            {
                System.out.println(e.toString());
            }
            
        }
    }//GEN-LAST:event_btnAffectedActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        pnlCovidAffect.setVisible(false);
        tblVaccinedPerson.setVisible(true);
        jScrollPane1.setVisible(true);
        btnCovidAffect1.setVisible(true);
        btnDelete.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vaccinedPersons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vaccinedPersons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vaccinedPersons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vaccinedPersons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vaccinedPersons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAffected;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCovidAffect1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAffectedPName;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lbltotalVP;
    private javax.swing.JPanel pnlCovidAffect;
    private javax.swing.JTable tblVaccinedPerson;
    private javax.swing.JTextField txtAffectedDate;
    private javax.swing.JTextField txtReportCode;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
